import { Edge } from "~/components/japanMap";

const dummyUsers = [
  {key: "北海道",
    value:[
      { id: 1, name: "山田太郎", prefecture: "北海道" },
      { id: 2, name: "田中花子", prefecture: "北海道" },
      { id: 3, name: "佐藤三郎", prefecture: "北海道" },
      { id: 4, name: "鈴木桃子", prefecture: "北海道" },
      { id: 5, name: "山本五郎", prefecture: "北海道" },
      { id: 6, name: "高橋愛子", prefecture: "北海道" },
      { id: 7, name: "渡辺二郎", prefecture: "北海道" },
      { id: 8, name: "伊藤桜子", prefecture: "北海道" },
      { id: 9, name: "中村四郎", prefecture: "北海道" },
      { id: 10, name: "小林優子", prefecture: "北海道" }
    ]
  },
  {key: "青森県",
    value:[
      { id: 11, name: "山田太郎", prefecture: "青森県" },
      { id: 12, name: "佐藤三郎", prefecture: "青森県" },
      { id: 13, name: "田中花子", prefecture: "青森県" },
      { id: 14, name: "鈴木桃子", prefecture: "青森県" },
      { id: 15, name: "山本五郎", prefecture: "青森県" },
      { id: 16, name: "高橋愛子", prefecture: "青森県" },
      { id: 17, name: "渡辺二郎", prefecture: "青森県" },
      { id: 18, name: "伊藤桜子", prefecture: "青森県" },
      { id: 19, name: "中村四郎", prefecture: "青森県" },
      { id: 20, name: "小林優子", prefecture: "青森県" }
    ]
  },
  {key: "岩手県",
    value:[
      { id: 21, name: "山田太郎", prefecture: "岩手県" },
      { id: 22, name: "佐藤三郎", prefecture: "岩手県" },
      { id: 23, name: "鈴木桃子", prefecture: "岩手県" },
      { id: 24, name: "田中花子", prefecture: "岩手県" },
      { id: 25, name: "山本五郎", prefecture: "岩手県" },
      { id: 26, name: "高橋愛子", prefecture: "岩手県" },
      { id: 27, name: "渡辺二郎", prefecture: "岩手県" },
      { id: 28, name: "伊藤桜子", prefecture: "岩手県" },
      { id: 29, name: "中村四郎", prefecture: "岩手県" },
      { id: 30, name: "小林優子", prefecture: "岩手県" }
    ]
  },
  {key: "宮城県",
    value:[
      { id: 31, name: "山田太郎", prefecture: "宮城県" },
      { id: 32, name: "佐藤三郎", prefecture: "宮城県" },
      { id: 33, name: "鈴木桃子", prefecture: "宮城県" },
      { id: 34, name: "山本五郎", prefecture: "宮城県" },
      { id: 35, name: "田中花子", prefecture: "宮城県" },
      { id: 36, name: "高橋愛子", prefecture: "宮城県" },
      { id: 37, name: "渡辺二郎", prefecture: "宮城県" },
      { id: 38, name: "伊藤桜子", prefecture: "宮城県" },
      { id: 39, name: "中村四郎", prefecture: "宮城県" },
      { id: 40, name: "小林優子", prefecture: "宮城県" }
    ]
  },
  {key: "秋田県",
    value:[
      { id: 41, name: "山田太郎", prefecture: "秋田県" },
      { id: 42, name: "佐藤三郎", prefecture: "秋田県" },
      { id: 43, name: "鈴木桃子", prefecture: "秋田県" },
      { id: 44, name: "山本五郎", prefecture: "秋田県" },
      { id: 45, name: "高橋愛子", prefecture: "秋田県" },
      { id: 46, name: "田中花子", prefecture: "秋田県" },
      { id: 47, name: "渡辺二郎", prefecture: "秋田県" },
      { id: 48, name: "伊藤桜子", prefecture: "秋田県" },
      { id: 49, name: "中村四郎", prefecture: "秋田県" },
      { id: 40, name: "小林優子", prefecture: "秋田県" }
    ]
  },
  {key: "山形県",
    value:[
      { id: 51, name: "山田太郎", prefecture: "山形県" },
      { id: 52, name: "佐藤三郎", prefecture: "山形県" },
      { id: 53, name: "鈴木桃子", prefecture: "山形県" },
      { id: 54, name: "山本五郎", prefecture: "山形県" },
      { id: 55, name: "高橋愛子", prefecture: "山形県" },
      { id: 56, name: "渡辺二郎", prefecture: "山形県" },
      { id: 57, name: "田中花子", prefecture: "山形県" },
      { id: 58, name: "伊藤桜子", prefecture: "山形県" },
      { id: 59, name: "中村四郎", prefecture: "山形県" },
      { id: 60, name: "小林優子", prefecture: "山形県" }
    ]
  },
  {key: "福島県",
    value:[
      { id: 61, name: "山田太郎", prefecture: "福島県" },
      { id: 62, name: "佐藤三郎", prefecture: "福島県" },
      { id: 63, name: "鈴木桃子", prefecture: "福島県" },
      { id: 64, name: "山本五郎", prefecture: "福島県" },
      { id: 65, name: "高橋愛子", prefecture: "福島県" },
      { id: 66, name: "渡辺二郎", prefecture: "福島県" },
      { id: 67, name: "伊藤桜子", prefecture: "福島県" },
      { id: 68, name: "田中花子", prefecture: "福島県" },
      { id: 69, name: "中村四郎", prefecture: "福島県" },
      { id: 70, name: "小林優子", prefecture: "福島県" }
    ]
  },
  {key: "茨城県",
    value:[
      { id: 71, name: "山田太郎", prefecture: "茨城県" },
      { id: 72, name: "佐藤三郎", prefecture: "茨城県" },
      { id: 73, name: "鈴木桃子", prefecture: "茨城県" },
      { id: 74, name: "山本五郎", prefecture: "茨城県" },
      { id: 75, name: "高橋愛子", prefecture: "茨城県" },
      { id: 76, name: "渡辺二郎", prefecture: "茨城県" },
      { id: 77, name: "伊藤桜子", prefecture: "茨城県" },
      { id: 78, name: "中村四郎", prefecture: "茨城県" },
      { id: 79, name: "田中花子", prefecture: "茨城県" },
      { id: 80, name: "小林優子", prefecture: "茨城県" }
    ]
  },
  {key: "栃木県",
    value:[
      { id: 81, name: "山田太郎", prefecture: "栃木県" },
      { id: 82, name: "佐藤三郎", prefecture: "栃木県" },
      { id: 83, name: "鈴木桃子", prefecture: "栃木県" },
      { id: 84, name: "山本五郎", prefecture: "栃木県" },
      { id: 85, name: "高橋愛子", prefecture: "栃木県" },
      { id: 86, name: "渡辺二郎", prefecture: "栃木県" },
      { id: 87, name: "伊藤桜子", prefecture: "栃木県" },
      { id: 88, name: "中村四郎", prefecture: "栃木県" },
      { id: 89, name: "小林優子", prefecture: "栃木県" },
      { id: 80, name: "田中花子", prefecture: "栃木県" },
    ]
  },
  {key: "群馬県",
    value:[
      { id: 91, name: "山田太郎", prefecture: "群馬県" },
      { id: 92, name: "田中花子", prefecture: "群馬県" },
      { id: 93, name: "鈴木桃子", prefecture: "群馬県" },
      { id: 94, name: "佐藤三郎", prefecture: "群馬県" },
      { id: 95, name: "山本五郎", prefecture: "群馬県" },
      { id: 96, name: "高橋愛子", prefecture: "群馬県" },
      { id: 97, name: "渡辺二郎", prefecture: "群馬県" },
      { id: 98, name: "伊藤桜子", prefecture: "群馬県" },
      { id: 99, name: "中村四郎", prefecture: "群馬県" },
      { id: 100, name: "小林優子", prefecture: "群馬県" }
    ]
  },
  {key: "埼玉県",
    value:[
      { id: 101, name: "山田太郎", prefecture: "埼玉県" },
      { id: 102, name: "田中花子", prefecture: "埼玉県" },
      { id: 103, name: "鈴木桃子", prefecture: "埼玉県" },
      { id: 104, name: "山本五郎", prefecture: "埼玉県" },
      { id: 105, name: "佐藤三郎", prefecture: "埼玉県" },
      { id: 106, name: "高橋愛子", prefecture: "埼玉県" },
      { id: 107, name: "渡辺二郎", prefecture: "埼玉県" },
      { id: 108, name: "伊藤桜子", prefecture: "埼玉県" },
      { id: 109, name: "中村四郎", prefecture: "埼玉県" },
      { id: 110, name: "小林優子", prefecture: "埼玉県" }
    ]
  },
  {key: "千葉県",
    value:[
      { id: 111, name: "山田太郎", prefecture: "千葉県" },
      { id: 112, name: "田中花子", prefecture: "千葉県" },
      { id: 113, name: "鈴木桃子", prefecture: "千葉県" },
      { id: 114, name: "山本五郎", prefecture: "千葉県" },
      { id: 115, name: "高橋愛子", prefecture: "千葉県" },
      { id: 116, name: "佐藤三郎", prefecture: "千葉県" },
      { id: 117, name: "渡辺二郎", prefecture: "千葉県" },
      { id: 118, name: "伊藤桜子", prefecture: "千葉県" },
      { id: 119, name: "中村四郎", prefecture: "千葉県" },
      { id: 120, name: "小林優子", prefecture: "千葉県" }
    ]
  },
  {key: "東京都",
    value:[
      { id: 121, name: "山田太郎", prefecture: "東京都" },
      { id: 122, name: "田中花子", prefecture: "東京都" },
      { id: 123, name: "鈴木桃子", prefecture: "東京都" },
      { id: 124, name: "山本五郎", prefecture: "東京都" },
      { id: 125, name: "高橋愛子", prefecture: "東京都" },
      { id: 126, name: "渡辺二郎", prefecture: "東京都" },
      { id: 127, name: "佐藤三郎", prefecture: "東京都" },
      { id: 128, name: "伊藤桜子", prefecture: "東京都" },
      { id: 129, name: "中村四郎", prefecture: "東京都" },
      { id: 130, name: "小林優子", prefecture: "東京都" }
    ]
  },
  {key: "神奈川県",
    value:[
      { id: 131, name: "山田太郎", prefecture: "神奈川県" },
      { id: 132, name: "田中花子", prefecture: "神奈川県" },
      { id: 133, name: "鈴木桃子", prefecture: "神奈川県" },
      { id: 134, name: "山本五郎", prefecture: "神奈川県" },
      { id: 135, name: "高橋愛子", prefecture: "神奈川県" },
      { id: 136, name: "渡辺二郎", prefecture: "神奈川県" },
      { id: 137, name: "伊藤桜子", prefecture: "神奈川県" },
      { id: 138, name: "佐藤三郎", prefecture: "神奈川県" },
      { id: 139, name: "中村四郎", prefecture: "神奈川県" },
      { id: 140, name: "小林優子", prefecture: "神奈川県" }
    ]
  },
  {key: "新潟県",
    value:[
      { id: 141, name: "山田太郎", prefecture: "新潟県" },
      { id: 142, name: "田中花子", prefecture: "新潟県" },
      { id: 143, name: "鈴木桃子", prefecture: "新潟県" },
      { id: 144, name: "山本五郎", prefecture: "新潟県" },
      { id: 145, name: "高橋愛子", prefecture: "新潟県" },
      { id: 146, name: "渡辺二郎", prefecture: "新潟県" },
      { id: 147, name: "伊藤桜子", prefecture: "新潟県" },
      { id: 148, name: "中村四郎", prefecture: "新潟県" },
      { id: 149, name: "佐藤三郎", prefecture: "新潟県" },
      { id: 150, name: "小林優子", prefecture: "新潟県" }
    ]
  },
  {key: "富山県",
    value:[
      { id: 151, name: "山田太郎", prefecture: "富山県" },
      { id: 152, name: "田中花子", prefecture: "富山県" },
      { id: 153, name: "鈴木桃子", prefecture: "富山県" },
      { id: 154, name: "山本五郎", prefecture: "富山県" },
      { id: 155, name: "高橋愛子", prefecture: "富山県" },
      { id: 156, name: "渡辺二郎", prefecture: "富山県" },
      { id: 157, name: "伊藤桜子", prefecture: "富山県" },
      { id: 158, name: "中村四郎", prefecture: "富山県" },
      { id: 159, name: "小林優子", prefecture: "富山県" },
      { id: 160, name: "佐藤三郎", prefecture: "富山県" },
    ]
  },
  {key: "石川県",
    value:[
      { id: 161, name: "山田太郎", prefecture: "石川県" },
      { id: 162, name: "田中花子", prefecture: "石川県" },
      { id: 163, name: "佐藤三郎", prefecture: "石川県" },
      { id: 164, name: "山本五郎", prefecture: "石川県" },
      { id: 165, name: "鈴木桃子", prefecture: "石川県" },
      { id: 166, name: "高橋愛子", prefecture: "石川県" },
      { id: 167, name: "渡辺二郎", prefecture: "石川県" },
      { id: 168, name: "伊藤桜子", prefecture: "石川県" },
      { id: 169, name: "中村四郎", prefecture: "石川県" },
      { id: 170, name: "小林優子", prefecture: "石川県" }
    ]
  },
  {key: "福井県",
    value:[
      { id: 171, name: "山田太郎", prefecture: "福井県" },
      { id: 172, name: "田中花子", prefecture: "福井県" },
      { id: 173, name: "佐藤三郎", prefecture: "福井県" },
      { id: 174, name: "山本五郎", prefecture: "福井県" },
      { id: 175, name: "高橋愛子", prefecture: "福井県" },
      { id: 176, name: "鈴木桃子", prefecture: "福井県" },
      { id: 177, name: "渡辺二郎", prefecture: "福井県" },
      { id: 178, name: "伊藤桜子", prefecture: "福井県" },
      { id: 179, name: "中村四郎", prefecture: "福井県" },
      { id: 180, name: "小林優子", prefecture: "福井県" }
    ]
  },
  {key: "山梨県",
    value:[
      { id: 181, name: "山田太郎", prefecture: "山梨県" },
      { id: 182, name: "田中花子", prefecture: "山梨県" },
      { id: 183, name: "佐藤三郎", prefecture: "山梨県" },
      { id: 184, name: "山本五郎", prefecture: "山梨県" },
      { id: 185, name: "高橋愛子", prefecture: "山梨県" },
      { id: 186, name: "渡辺二郎", prefecture: "山梨県" },
      { id: 187, name: "鈴木桃子", prefecture: "山梨県" },
      { id: 188, name: "伊藤桜子", prefecture: "山梨県" },
      { id: 189, name: "中村四郎", prefecture: "山梨県" },
      { id: 190, name: "小林優子", prefecture: "山梨県" }
    ]
  },
  {key: "長野県",
    value:[
      { id: 191, name: "山田太郎", prefecture: "長野県" },
      { id: 192, name: "田中花子", prefecture: "長野県" },
      { id: 193, name: "佐藤三郎", prefecture: "長野県" },
      { id: 194, name: "山本五郎", prefecture: "長野県" },
      { id: 195, name: "高橋愛子", prefecture: "長野県" },
      { id: 196, name: "渡辺二郎", prefecture: "長野県" },
      { id: 197, name: "伊藤桜子", prefecture: "長野県" },
      { id: 198, name: "鈴木桃子", prefecture: "長野県" },
      { id: 199, name: "中村四郎", prefecture: "長野県" },
      { id: 200, name: "小林優子", prefecture: "長野県" }
    ]
  },
  {key: "岐阜県",
    value:[
      { id: 201, name: "山田太郎", prefecture: "岐阜県" },
      { id: 202, name: "田中花子", prefecture: "岐阜県" },
      { id: 203, name: "佐藤三郎", prefecture: "岐阜県" },
      { id: 204, name: "山本五郎", prefecture: "岐阜県" },
      { id: 205, name: "高橋愛子", prefecture: "岐阜県" },
      { id: 206, name: "渡辺二郎", prefecture: "岐阜県" },
      { id: 207, name: "伊藤桜子", prefecture: "岐阜県" },
      { id: 208, name: "中村四郎", prefecture: "岐阜県" },
      { id: 209, name: "鈴木桃子", prefecture: "岐阜県" },
      { id: 210, name: "小林優子", prefecture: "岐阜県" }
    ]
  },
  {key: "静岡県",
    value:[
      { id: 211, name: "山田太郎", prefecture: "静岡県" },
      { id: 212, name: "田中花子", prefecture: "静岡県" },
      { id: 213, name: "佐藤三郎", prefecture: "静岡県" },
      { id: 214, name: "山本五郎", prefecture: "静岡県" },
      { id: 215, name: "高橋愛子", prefecture: "静岡県" },
      { id: 216, name: "渡辺二郎", prefecture: "静岡県" },
      { id: 217, name: "伊藤桜子", prefecture: "静岡県" },
      { id: 218, name: "中村四郎", prefecture: "静岡県" },
      { id: 219, name: "小林優子", prefecture: "静岡県" },
      { id: 220, name: "鈴木桃子", prefecture: "静岡県" },
    ]
  },
  {key: "愛知県",
    value:[
      { id: 221, name: "山田太郎", prefecture: "愛知県" },
      { id: 222, name: "田中花子", prefecture: "愛知県" },
      { id: 223, name: "佐藤三郎", prefecture: "愛知県" },
      { id: 224, name: "鈴木桃子", prefecture: "愛知県" },
      { id: 225, name: "高橋愛子", prefecture: "愛知県" },
      { id: 226, name: "山本五郎", prefecture: "愛知県" },
      { id: 227, name: "渡辺二郎", prefecture: "愛知県" },
      { id: 228, name: "伊藤桜子", prefecture: "愛知県" },
      { id: 229, name: "中村四郎", prefecture: "愛知県" },
      { id: 230, name: "小林優子", prefecture: "愛知県" }
    ]
  },
  {key: "三重県",
    value:[
      { id: 231, name: "山田太郎", prefecture: "三重県" },
      { id: 232, name: "田中花子", prefecture: "三重県" },
      { id: 233, name: "佐藤三郎", prefecture: "三重県" },
      { id: 234, name: "鈴木桃子", prefecture: "三重県" },
      { id: 235, name: "高橋愛子", prefecture: "三重県" },
      { id: 236, name: "渡辺二郎", prefecture: "三重県" },
      { id: 237, name: "山本五郎", prefecture: "三重県" },
      { id: 238, name: "伊藤桜子", prefecture: "三重県" },
      { id: 239, name: "中村四郎", prefecture: "三重県" },
      { id: 240, name: "小林優子", prefecture: "三重県" }
    ]
  },
  {key: "滋賀県",
    value:[
      { id: 261, name: "山田太郎", prefecture: "滋賀県" },
      { id: 242, name: "田中花子", prefecture: "滋賀県" },
      { id: 243, name: "佐藤三郎", prefecture: "滋賀県" },
      { id: 244, name: "鈴木桃子", prefecture: "滋賀県" },
      { id: 245, name: "高橋愛子", prefecture: "滋賀県" },
      { id: 246, name: "渡辺二郎", prefecture: "滋賀県" },
      { id: 247, name: "伊藤桜子", prefecture: "滋賀県" },
      { id: 248, name: "山本五郎", prefecture: "滋賀県" },
      { id: 249, name: "中村四郎", prefecture: "滋賀県" },
      { id: 250, name: "小林優子", prefecture: "滋賀県" }
    ]
  },
  {key: "京都府",
    value:[
      { id: 251, name: "山田太郎", prefecture: "京都府" },
      { id: 252, name: "田中花子", prefecture: "京都府" },
      { id: 253, name: "佐藤三郎", prefecture: "京都府" },
      { id: 254, name: "鈴木桃子", prefecture: "京都府" },
      { id: 255, name: "高橋愛子", prefecture: "京都府" },
      { id: 256, name: "渡辺二郎", prefecture: "京都府" },
      { id: 257, name: "伊藤桜子", prefecture: "京都府" },
      { id: 258, name: "中村四郎", prefecture: "京都府" },
      { id: 259, name: "山本五郎", prefecture: "京都府" },
      { id: 260, name: "小林優子", prefecture: "京都府" }
    ]
  },
  {key: "大阪府",
    value:[
      { id: 261, name: "山田太郎", prefecture: "大阪府" },
      { id: 262, name: "田中花子", prefecture: "大阪府" },
      { id: 263, name: "佐藤三郎", prefecture: "大阪府" },
      { id: 264, name: "鈴木桃子", prefecture: "大阪府" },
      { id: 265, name: "高橋愛子", prefecture: "大阪府" },
      { id: 266, name: "渡辺二郎", prefecture: "大阪府" },
      { id: 267, name: "伊藤桜子", prefecture: "大阪府" },
      { id: 268, name: "中村四郎", prefecture: "大阪府" },
      { id: 269, name: "小林優子", prefecture: "大阪府" },
      { id: 270, name: "山本五郎", prefecture: "大阪府" },
    ]
  },
  {key: "兵庫県",
    value:[
      { id: 271, name: "山田太郎", prefecture: "兵庫県" },
      { id: 272, name: "田中花子", prefecture: "兵庫県" },
      { id: 273, name: "佐藤三郎", prefecture: "兵庫県" },
      { id: 274, name: "鈴木桃子", prefecture: "兵庫県" },
      { id: 275, name: "山本五郎", prefecture: "兵庫県" },
      { id: 276, name: "渡辺二郎", prefecture: "兵庫県" },
      { id: 277, name: "高橋愛子", prefecture: "兵庫県" },
      { id: 278, name: "伊藤桜子", prefecture: "兵庫県" },
      { id: 279, name: "中村四郎", prefecture: "兵庫県" },
      { id: 280, name: "小林優子", prefecture: "兵庫県" }
    ]
  },
  {key: "奈良県",
    value:[
      { id: 281, name: "山田太郎", prefecture: "奈良県" },
      { id: 282, name: "田中花子", prefecture: "奈良県" },
      { id: 283, name: "佐藤三郎", prefecture: "奈良県" },
      { id: 284, name: "鈴木桃子", prefecture: "奈良県" },
      { id: 285, name: "山本五郎", prefecture: "奈良県" },
      { id: 286, name: "渡辺二郎", prefecture: "奈良県" },
      { id: 287, name: "伊藤桜子", prefecture: "奈良県" },
      { id: 288, name: "高橋愛子", prefecture: "奈良県" },
      { id: 289, name: "中村四郎", prefecture: "奈良県" },
      { id: 290, name: "小林優子", prefecture: "奈良県" }
    ]
  },
  {key: "和歌山県",
    value:[
      { id: 291, name: "山田太郎", prefecture: "和歌山県" },
      { id: 292, name: "田中花子", prefecture: "和歌山県" },
      { id: 293, name: "佐藤三郎", prefecture: "和歌山県" },
      { id: 294, name: "鈴木桃子", prefecture: "和歌山県" },
      { id: 295, name: "山本五郎", prefecture: "和歌山県" },
      { id: 296, name: "渡辺二郎", prefecture: "和歌山県" },
      { id: 297, name: "伊藤桜子", prefecture: "和歌山県" },
      { id: 298, name: "中村四郎", prefecture: "和歌山県" },
      { id: 299, name: "高橋愛子", prefecture: "和歌山県" },
      { id: 300, name: "小林優子", prefecture: "和歌山県" }
    ]
  },
  {key: "鳥取県",
    value:[
      { id: 301, name: "山田太郎", prefecture: "鳥取県" },
      { id: 302, name: "田中花子", prefecture: "鳥取県" },
      { id: 303, name: "佐藤三郎", prefecture: "鳥取県" },
      { id: 304, name: "鈴木桃子", prefecture: "鳥取県" },
      { id: 305, name: "山本五郎", prefecture: "鳥取県" },
      { id: 306, name: "渡辺二郎", prefecture: "鳥取県" },
      { id: 307, name: "伊藤桜子", prefecture: "鳥取県" },
      { id: 308, name: "中村四郎", prefecture: "鳥取県" },
      { id: 309, name: "小林優子", prefecture: "鳥取県" },
      { id: 300, name: "高橋愛子", prefecture: "鳥取県" },
    ]
  },
  {key: "島根県",
    value:[
      { id: 311, name: "山田太郎", prefecture: "島根県" },
      { id: 312, name: "田中花子", prefecture: "島根県" },
      { id: 313, name: "佐藤三郎", prefecture: "島根県" },
      { id: 314, name: "鈴木桃子", prefecture: "島根県" },
      { id: 315, name: "山本五郎", prefecture: "島根県" },
      { id: 316, name: "高橋愛子", prefecture: "島根県" },
      { id: 317, name: "伊藤桜子", prefecture: "島根県" },
      { id: 318, name: "渡辺二郎", prefecture: "島根県" },
      { id: 319, name: "中村四郎", prefecture: "島根県" },
      { id: 320, name: "小林優子", prefecture: "島根県" }
    ]
  },
  {key: "岡山県",
    value:[
      { id: 321, name: "山田太郎", prefecture: "岡山県" },
      { id: 322, name: "田中花子", prefecture: "岡山県" },
      { id: 323, name: "佐藤三郎", prefecture: "岡山県" },
      { id: 324, name: "鈴木桃子", prefecture: "岡山県" },
      { id: 325, name: "山本五郎", prefecture: "岡山県" },
      { id: 326, name: "高橋愛子", prefecture: "岡山県" },
      { id: 327, name: "伊藤桜子", prefecture: "岡山県" },
      { id: 328, name: "中村四郎", prefecture: "岡山県" },
      { id: 329, name: "渡辺二郎", prefecture: "岡山県" },
      { id: 330, name: "小林優子", prefecture: "岡山県" }
    ]
  },
  {key: "広島県",
    value:[
      { id: 331, name: "山田太郎", prefecture: "広島県" },
      { id: 332, name: "田中花子", prefecture: "広島県" },
      { id: 333, name: "佐藤三郎", prefecture: "広島県" },
      { id: 334, name: "鈴木桃子", prefecture: "広島県" },
      { id: 335, name: "山本五郎", prefecture: "広島県" },
      { id: 336, name: "高橋愛子", prefecture: "広島県" },
      { id: 337, name: "伊藤桜子", prefecture: "広島県" },
      { id: 338, name: "中村四郎", prefecture: "広島県" },
      { id: 339, name: "小林優子", prefecture: "広島県" },
      { id: 340, name: "渡辺二郎", prefecture: "広島県" },
    ]
  },
  {key: "山口県",
    value:[
      { id: 341, name: "山田太郎", prefecture: "山口県" },
      { id: 342, name: "田中花子", prefecture: "山口県" },
      { id: 343, name: "佐藤三郎", prefecture: "山口県" },
      { id: 344, name: "鈴木桃子", prefecture: "山口県" },
      { id: 345, name: "山本五郎", prefecture: "山口県" },
      { id: 346, name: "高橋愛子", prefecture: "山口県" },
      { id: 347, name: "渡辺二郎", prefecture: "山口県" },
      { id: 348, name: "中村四郎", prefecture: "山口県" },
      { id: 349, name: "伊藤桜子", prefecture: "山口県" },
      { id: 350, name: "小林優子", prefecture: "山口県" }
    ]
  },
  {key: "徳島県",
    value:[
      { id: 351, name: "山田太郎", prefecture: "徳島県" },
      { id: 352, name: "田中花子", prefecture: "徳島県" },
      { id: 353, name: "佐藤三郎", prefecture: "徳島県" },
      { id: 354, name: "鈴木桃子", prefecture: "徳島県" },
      { id: 355, name: "山本五郎", prefecture: "徳島県" },
      { id: 356, name: "高橋愛子", prefecture: "徳島県" },
      { id: 357, name: "渡辺二郎", prefecture: "徳島県" },
      { id: 358, name: "中村四郎", prefecture: "徳島県" },
      { id: 359, name: "小林優子", prefecture: "徳島県" },
      { id: 360, name: "伊藤桜子", prefecture: "徳島県" },
    ]
  },
  {key: "香川県",
    value:[
      { id: 361, name: "山田太郎", prefecture: "香川県" },
      { id: 362, name: "田中花子", prefecture: "香川県" },
      { id: 363, name: "佐藤三郎", prefecture: "香川県" },
      { id: 364, name: "鈴木桃子", prefecture: "香川県" },
      { id: 365, name: "山本五郎", prefecture: "香川県" },
      { id: 366, name: "高橋愛子", prefecture: "香川県" },
      { id: 367, name: "渡辺二郎", prefecture: "香川県" },
      { id: 368, name: "伊藤桜子", prefecture: "香川県" },
      { id: 369, name: "小林優子", prefecture: "香川県" },
      { id: 370, name: "中村四郎", prefecture: "香川県" },
    ]
  },
  {key: "愛媛県",
    value:[
      { id: 371, name: "田中花子", prefecture: "愛媛県" },
      { id: 372, name: "山田太郎", prefecture: "愛媛県" },
      { id: 373, name: "佐藤三郎", prefecture: "愛媛県" },
      { id: 374, name: "鈴木桃子", prefecture: "愛媛県" },
      { id: 375, name: "山本五郎", prefecture: "愛媛県" },
      { id: 376, name: "高橋愛子", prefecture: "愛媛県" },
      { id: 377, name: "渡辺二郎", prefecture: "愛媛県" },
      { id: 378, name: "伊藤桜子", prefecture: "愛媛県" },
      { id: 379, name: "中村四郎", prefecture: "愛媛県" },
      { id: 380, name: "小林優子", prefecture: "愛媛県" }
    ]
  },
  {key: "高知県",
    value:[
      { id: 381, name: "田中花子", prefecture: "高知県" },
      { id: 382, name: "佐藤三郎", prefecture: "高知県" },
      { id: 383, name: "山田太郎", prefecture: "高知県" },
      { id: 384, name: "鈴木桃子", prefecture: "高知県" },
      { id: 385, name: "山本五郎", prefecture: "高知県" },
      { id: 386, name: "高橋愛子", prefecture: "高知県" },
      { id: 387, name: "渡辺二郎", prefecture: "高知県" },
      { id: 388, name: "伊藤桜子", prefecture: "高知県" },
      { id: 389, name: "中村四郎", prefecture: "高知県" },
      { id: 380, name: "小林優子", prefecture: "高知県" }
    ]
  },
  {key: "福岡県",
    value:[
      { id: 391, name: "田中花子", prefecture: "福岡県" },
      { id: 392, name: "佐藤三郎", prefecture: "福岡県" },
      { id: 393, name: "鈴木桃子", prefecture: "福岡県" },
      { id: 394, name: "山田太郎", prefecture: "福岡県" },
      { id: 395, name: "山本五郎", prefecture: "福岡県" },
      { id: 396, name: "高橋愛子", prefecture: "福岡県" },
      { id: 397, name: "渡辺二郎", prefecture: "福岡県" },
      { id: 398, name: "伊藤桜子", prefecture: "福岡県" },
      { id: 399, name: "中村四郎", prefecture: "福岡県" },
      { id: 400, name: "小林優子", prefecture: "福岡県" }
    ]
  },
  {key: "佐賀県",
    value:[
      { id: 401, name: "田中花子", prefecture: "佐賀県" },
      { id: 402, name: "佐藤三郎", prefecture: "佐賀県" },
      { id: 403, name: "鈴木桃子", prefecture: "佐賀県" },
      { id: 404, name: "山本五郎", prefecture: "佐賀県" },
      { id: 405, name: "山田太郎", prefecture: "佐賀県" },
      { id: 406, name: "高橋愛子", prefecture: "佐賀県" },
      { id: 407, name: "渡辺二郎", prefecture: "佐賀県" },
      { id: 408, name: "伊藤桜子", prefecture: "佐賀県" },
      { id: 409, name: "中村四郎", prefecture: "佐賀県" },
      { id: 410, name: "小林優子", prefecture: "佐賀県" }
    ]
  },
  {key: "長崎県",
    value:[
      { id: 411, name: "田中花子", prefecture: "長崎県" },
      { id: 412, name: "佐藤三郎", prefecture: "長崎県" },
      { id: 413, name: "鈴木桃子", prefecture: "長崎県" },
      { id: 414, name: "山本五郎", prefecture: "長崎県" },
      { id: 415, name: "高橋愛子", prefecture: "長崎県" },
      { id: 416, name: "山田太郎", prefecture: "長崎県" },
      { id: 417, name: "渡辺二郎", prefecture: "長崎県" },
      { id: 418, name: "伊藤桜子", prefecture: "長崎県" },
      { id: 419, name: "中村四郎", prefecture: "長崎県" },
      { id: 420, name: "小林優子", prefecture: "長崎県" }
    ]
  },
  {key: "熊本県",
    value:[
      { id: 421, name: "田中花子", prefecture: "熊本県" },
      { id: 422, name: "佐藤三郎", prefecture: "熊本県" },
      { id: 423, name: "鈴木桃子", prefecture: "熊本県" },
      { id: 424, name: "山本五郎", prefecture: "熊本県" },
      { id: 425, name: "高橋愛子", prefecture: "熊本県" },
      { id: 426, name: "渡辺二郎", prefecture: "熊本県" },
      { id: 427, name: "山田太郎", prefecture: "熊本県" },
      { id: 428, name: "伊藤桜子", prefecture: "熊本県" },
      { id: 429, name: "中村四郎", prefecture: "熊本県" },
      { id: 430, name: "小林優子", prefecture: "熊本県" }
    ]
  },
  {key: "大分県",
    value:[
      { id: 431, name: "田中花子", prefecture: "大分県" },
      { id: 432, name: "佐藤三郎", prefecture: "大分県" },
      { id: 433, name: "鈴木桃子", prefecture: "大分県" },
      { id: 434, name: "山本五郎", prefecture: "大分県" },
      { id: 435, name: "高橋愛子", prefecture: "大分県" },
      { id: 436, name: "渡辺二郎", prefecture: "大分県" },
      { id: 437, name: "伊藤桜子", prefecture: "大分県" },
      { id: 438, name: "山田太郎", prefecture: "大分県" },
      { id: 439, name: "中村四郎", prefecture: "大分県" },
      { id: 440, name: "小林優子", prefecture: "大分県" }
    ]
  },
  {key: "宮崎県",
    value:[
      { id: 441, name: "田中花子", prefecture: "宮崎県" },
      { id: 442, name: "佐藤三郎", prefecture: "宮崎県" },
      { id: 443, name: "鈴木桃子", prefecture: "宮崎県" },
      { id: 444, name: "山本五郎", prefecture: "宮崎県" },
      { id: 445, name: "高橋愛子", prefecture: "宮崎県" },
      { id: 446, name: "渡辺二郎", prefecture: "宮崎県" },
      { id: 447, name: "伊藤桜子", prefecture: "宮崎県" },
      { id: 448, name: "中村四郎", prefecture: "宮崎県" },
      { id: 449, name: "山田太郎", prefecture: "宮崎県" },
      { id: 450, name: "小林優子", prefecture: "宮崎県" }
    ]
  },
  {key: "鹿児島県",
    value:[
      { id: 451, name: "田中花子", prefecture: "鹿児島県" },
      { id: 452, name: "佐藤三郎", prefecture: "鹿児島県" },
      { id: 453, name: "鈴木桃子", prefecture: "鹿児島県" },
      { id: 454, name: "山本五郎", prefecture: "鹿児島県" },
      { id: 455, name: "高橋愛子", prefecture: "鹿児島県" },
      { id: 456, name: "渡辺二郎", prefecture: "鹿児島県" },
      { id: 457, name: "伊藤桜子", prefecture: "鹿児島県" },
      { id: 458, name: "中村四郎", prefecture: "鹿児島県" },
      { id: 459, name: "小林優子", prefecture: "鹿児島県" },
      { id: 460, name: "山田太郎", prefecture: "鹿児島県" },
    ]
  },
  {key: "沖縄県",
    value:[
      { id: 461, name: "山田太郎", prefecture: "沖縄県" },
      { id: 462, name: "田中花子", prefecture: "沖縄県" },
      { id: 463, name: "佐藤三郎", prefecture: "沖縄県" },
      { id: 464, name: "鈴木桃子", prefecture: "沖縄県" },
      { id: 465, name: "山本五郎", prefecture: "沖縄県" },
      { id: 466, name: "高橋愛子", prefecture: "沖縄県" },
      { id: 467, name: "渡辺二郎", prefecture: "沖縄県" },
      { id: 468, name: "伊藤桜子", prefecture: "沖縄県" },
      { id: 469, name: "中村四郎", prefecture: "沖縄県" },
      { id: 470, name: "小林優子", prefecture: "沖縄県" }
    ]
  },
]

const OFFLINE_COLOR = "#ffff7f20";
const ONLINE_COLOR = "#7f7fff20";

const dummyEdge: Edge[] = [
  // OFFLINE
  { nodes: ["北海道",	"青森県"], color: OFFLINE_COLOR},
  { nodes: ["北海道",	"岩手県"], color: OFFLINE_COLOR},
  { nodes: ["北海道",	"宮城県"], color: OFFLINE_COLOR},
  { nodes: ["北海道",	"秋田県"], color: OFFLINE_COLOR},
  { nodes: ["北海道",	"山形県"], color: OFFLINE_COLOR},
  { nodes: ["北海道",	"福島県"], color: OFFLINE_COLOR},
  { nodes: ["北海道",	"茨城県"], color: OFFLINE_COLOR},
  { nodes: ["北海道",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["北海道",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["北海道",	"埼玉県"], color: OFFLINE_COLOR},
  
  { nodes: ["青森県",	"北海道"], color: OFFLINE_COLOR},
  { nodes: ["青森県",	"岩手県"], color: OFFLINE_COLOR},
  { nodes: ["青森県",	"宮城県"], color: OFFLINE_COLOR},
  { nodes: ["青森県",	"秋田県"], color: OFFLINE_COLOR},
  { nodes: ["青森県",	"山形県"], color: OFFLINE_COLOR},
  { nodes: ["青森県",	"福島県"], color: OFFLINE_COLOR},
  { nodes: ["青森県",	"茨城県"], color: OFFLINE_COLOR},
  { nodes: ["青森県",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["青森県",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["青森県",	"埼玉県"], color: OFFLINE_COLOR},

  { nodes: ["岩手県",	"北海道"], color: OFFLINE_COLOR},
  { nodes: ["岩手県",	"青森県"], color: OFFLINE_COLOR},
  { nodes: ["岩手県",	"宮城県"], color: OFFLINE_COLOR},
  { nodes: ["岩手県",	"秋田県"], color: OFFLINE_COLOR},
  { nodes: ["岩手県",	"山形県"], color: OFFLINE_COLOR},
  { nodes: ["岩手県",	"福島県"], color: OFFLINE_COLOR},
  { nodes: ["岩手県",	"茨城県"], color: OFFLINE_COLOR},
  { nodes: ["岩手県",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["岩手県",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["岩手県",	"埼玉県"], color: OFFLINE_COLOR},

  { nodes: ["宮城県",	"北海道"], color: OFFLINE_COLOR},
  { nodes: ["宮城県",	"青森県"], color: OFFLINE_COLOR},
  { nodes: ["宮城県",	"岩手県"], color: OFFLINE_COLOR},
  { nodes: ["宮城県",	"秋田県"], color: OFFLINE_COLOR},
  { nodes: ["宮城県",	"山形県"], color: OFFLINE_COLOR},
  { nodes: ["宮城県",	"福島県"], color: OFFLINE_COLOR},
  { nodes: ["宮城県",	"茨城県"], color: OFFLINE_COLOR},
  { nodes: ["宮城県",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["宮城県",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["宮城県",	"埼玉県"], color: OFFLINE_COLOR},
    
  { nodes: ["秋田県",	"北海道"], color: OFFLINE_COLOR},
  { nodes: ["秋田県",	"青森県"], color: OFFLINE_COLOR},
  { nodes: ["秋田県",	"岩手県"], color: OFFLINE_COLOR},
  { nodes: ["秋田県",	"宮城県"], color: OFFLINE_COLOR},
  { nodes: ["秋田県",	"山形県"], color: OFFLINE_COLOR},
  { nodes: ["秋田県",	"福島県"], color: OFFLINE_COLOR},
  { nodes: ["秋田県",	"茨城県"], color: OFFLINE_COLOR},
  { nodes: ["秋田県",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["秋田県",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["秋田県",	"埼玉県"], color: OFFLINE_COLOR},
    
  { nodes: ["山形県",	"北海道"], color: OFFLINE_COLOR},
  { nodes: ["山形県",	"青森県"], color: OFFLINE_COLOR},
  { nodes: ["山形県",	"岩手県"], color: OFFLINE_COLOR},
  { nodes: ["山形県",	"宮城県"], color: OFFLINE_COLOR},
  { nodes: ["山形県",	"秋田県"], color: OFFLINE_COLOR},
  { nodes: ["山形県",	"福島県"], color: OFFLINE_COLOR},
  { nodes: ["山形県",	"茨城県"], color: OFFLINE_COLOR},
  { nodes: ["山形県",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["山形県",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["山形県",	"埼玉県"], color: OFFLINE_COLOR},
    
  { nodes: ["福島県",	"青森県"], color: OFFLINE_COLOR},
  { nodes: ["福島県",	"岩手県"], color: OFFLINE_COLOR},
  { nodes: ["福島県",	"宮城県"], color: OFFLINE_COLOR},
  { nodes: ["福島県",	"秋田県"], color: OFFLINE_COLOR},
  { nodes: ["福島県",	"山形県"], color: OFFLINE_COLOR},
  { nodes: ["福島県",	"茨城県"], color: OFFLINE_COLOR},
  { nodes: ["福島県",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["福島県",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["福島県",	"埼玉県"], color: OFFLINE_COLOR},
  { nodes: ["福島県",	"千葉県"], color: OFFLINE_COLOR},

  { nodes: ["茨城県",	"岩手県"], color: OFFLINE_COLOR},
  { nodes: ["茨城県",	"宮城県"], color: OFFLINE_COLOR},
  { nodes: ["茨城県",	"秋田県"], color: OFFLINE_COLOR},
  { nodes: ["茨城県",	"山形県"], color: OFFLINE_COLOR},
  { nodes: ["茨城県",	"福島県"], color: OFFLINE_COLOR},
  { nodes: ["茨城県",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["茨城県",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["茨城県",	"埼玉県"], color: OFFLINE_COLOR},
  { nodes: ["茨城県",	"千葉県"], color: OFFLINE_COLOR},
  { nodes: ["茨城県",	"東京都"], color: OFFLINE_COLOR},
    
  { nodes: ["栃木県",	"宮城県"], color: OFFLINE_COLOR},
  { nodes: ["栃木県",	"秋田県"], color: OFFLINE_COLOR},
  { nodes: ["栃木県",	"山形県"], color: OFFLINE_COLOR},
  { nodes: ["栃木県",	"福島県"], color: OFFLINE_COLOR},
  { nodes: ["栃木県",	"茨城県"], color: OFFLINE_COLOR},
  { nodes: ["栃木県",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["栃木県",	"埼玉県"], color: OFFLINE_COLOR},
  { nodes: ["栃木県",	"千葉県"], color: OFFLINE_COLOR},
  { nodes: ["栃木県",	"東京都"], color: OFFLINE_COLOR},
  { nodes: ["栃木県",	"神奈川県"], color: OFFLINE_COLOR},
    
  { nodes: ["群馬県",	"秋田県"], color: OFFLINE_COLOR},
  { nodes: ["群馬県",	"山形県"], color: OFFLINE_COLOR},
  { nodes: ["群馬県",	"福島県"], color: OFFLINE_COLOR},
  { nodes: ["群馬県",	"茨城県"], color: OFFLINE_COLOR},
  { nodes: ["群馬県",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["群馬県",	"埼玉県"], color: OFFLINE_COLOR},
  { nodes: ["群馬県",	"千葉県"], color: OFFLINE_COLOR},
  { nodes: ["群馬県",	"東京都"], color: OFFLINE_COLOR},
  { nodes: ["群馬県",	"神奈川県"], color: OFFLINE_COLOR},
  { nodes: ["群馬県",	"新潟県"], color: OFFLINE_COLOR},
    
  { nodes: ["埼玉県",	"山形県"], color: OFFLINE_COLOR},
  { nodes: ["埼玉県",	"福島県"], color: OFFLINE_COLOR},
  { nodes: ["埼玉県",	"茨城県"], color: OFFLINE_COLOR},
  { nodes: ["埼玉県",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["埼玉県",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["埼玉県",	"千葉県"], color: OFFLINE_COLOR},
  { nodes: ["埼玉県",	"東京都"], color: OFFLINE_COLOR},
  { nodes: ["埼玉県",	"神奈川県"], color: OFFLINE_COLOR},
  { nodes: ["埼玉県",	"新潟県"], color: OFFLINE_COLOR},
  { nodes: ["埼玉県",	"富山県"], color: OFFLINE_COLOR},
    
  { nodes: ["千葉県",	"福島県"], color: OFFLINE_COLOR},
  { nodes: ["千葉県",	"茨城県"], color: OFFLINE_COLOR},
  { nodes: ["千葉県",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["千葉県",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["千葉県",	"埼玉県"], color: OFFLINE_COLOR},
  { nodes: ["千葉県",	"東京都"], color: OFFLINE_COLOR},
  { nodes: ["千葉県",	"神奈川県"], color: OFFLINE_COLOR},
  { nodes: ["千葉県",	"新潟県"], color: OFFLINE_COLOR},
  { nodes: ["千葉県",	"富山県"], color: OFFLINE_COLOR},
  { nodes: ["千葉県",	"石川県"], color: OFFLINE_COLOR},
    
  { nodes: ["東京都",	"茨城県"], color: OFFLINE_COLOR},
  { nodes: ["東京都",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["東京都",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["東京都",	"埼玉県"], color: OFFLINE_COLOR},
  { nodes: ["東京都",	"千葉県"], color: OFFLINE_COLOR},
  { nodes: ["東京都",	"神奈川県"], color: OFFLINE_COLOR},
  { nodes: ["東京都",	"新潟県"], color: OFFLINE_COLOR},
  { nodes: ["東京都",	"富山県"], color: OFFLINE_COLOR},
  { nodes: ["東京都",	"石川県"], color: OFFLINE_COLOR},
  { nodes: ["東京都",	"福井県"], color: OFFLINE_COLOR},
    
  { nodes: ["神奈川県",	"栃木県"], color: OFFLINE_COLOR},
  { nodes: ["神奈川県",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["神奈川県",	"埼玉県"], color: OFFLINE_COLOR},
  { nodes: ["神奈川県",	"千葉県"], color: OFFLINE_COLOR},
  { nodes: ["神奈川県",	"東京都"], color: OFFLINE_COLOR},
  { nodes: ["神奈川県",	"新潟県"], color: OFFLINE_COLOR},
  { nodes: ["神奈川県",	"富山県"], color: OFFLINE_COLOR},
  { nodes: ["神奈川県",	"石川県"], color: OFFLINE_COLOR},
  { nodes: ["神奈川県",	"福井県"], color: OFFLINE_COLOR},
  { nodes: ["神奈川県",	"山梨県"], color: OFFLINE_COLOR},
    
  { nodes: ["新潟県",	"群馬県"], color: OFFLINE_COLOR},
  { nodes: ["新潟県",	"埼玉県"], color: OFFLINE_COLOR},
  { nodes: ["新潟県",	"千葉県"], color: OFFLINE_COLOR},
  { nodes: ["新潟県",	"東京都"], color: OFFLINE_COLOR},
  { nodes: ["新潟県",	"神奈川県"], color: OFFLINE_COLOR},
  { nodes: ["新潟県",	"富山県"], color: OFFLINE_COLOR},
  { nodes: ["新潟県",	"石川県"], color: OFFLINE_COLOR},
  { nodes: ["新潟県",	"福井県"], color: OFFLINE_COLOR},
  { nodes: ["新潟県",	"山梨県"], color: OFFLINE_COLOR},
  { nodes: ["新潟県",	"長野県"], color: OFFLINE_COLOR},
    
  { nodes: ["富山県",	"埼玉県"], color: OFFLINE_COLOR},
  { nodes: ["富山県",	"千葉県"], color: OFFLINE_COLOR},
  { nodes: ["富山県",	"東京都"], color: OFFLINE_COLOR},
  { nodes: ["富山県",	"神奈川県"], color: OFFLINE_COLOR},
  { nodes: ["富山県",	"新潟県"], color: OFFLINE_COLOR},
  { nodes: ["富山県",	"石川県"], color: OFFLINE_COLOR},
  { nodes: ["富山県",	"福井県"], color: OFFLINE_COLOR},
  { nodes: ["富山県",	"山梨県"], color: OFFLINE_COLOR},
  { nodes: ["富山県",	"長野県"], color: OFFLINE_COLOR},
  { nodes: ["富山県",	"岐阜県"], color: OFFLINE_COLOR},
    
  { nodes: ["石川県",	"千葉県"], color: OFFLINE_COLOR},
  { nodes: ["石川県",	"東京都"], color: OFFLINE_COLOR},
  { nodes: ["石川県",	"神奈川県"], color: OFFLINE_COLOR},
  { nodes: ["石川県",	"新潟県"], color: OFFLINE_COLOR},
  { nodes: ["石川県",	"富山県"], color: OFFLINE_COLOR},
  { nodes: ["石川県",	"福井県"], color: OFFLINE_COLOR},
  { nodes: ["石川県",	"山梨県"], color: OFFLINE_COLOR},
  { nodes: ["石川県",	"長野県"], color: OFFLINE_COLOR},
  { nodes: ["石川県",	"岐阜県"], color: OFFLINE_COLOR},
  { nodes: ["石川県",	"静岡県"], color: OFFLINE_COLOR},
    
  { nodes: ["福井県",	"東京都"], color: OFFLINE_COLOR},
  { nodes: ["福井県",	"神奈川県"], color: OFFLINE_COLOR},
  { nodes: ["福井県",	"新潟県"], color: OFFLINE_COLOR},
  { nodes: ["福井県",	"富山県"], color: OFFLINE_COLOR},
  { nodes: ["福井県",	"石川県"], color: OFFLINE_COLOR},
  { nodes: ["福井県",	"山梨県"], color: OFFLINE_COLOR},
  { nodes: ["福井県",	"長野県"], color: OFFLINE_COLOR},
  { nodes: ["福井県",	"岐阜県"], color: OFFLINE_COLOR},
  { nodes: ["福井県",	"静岡県"], color: OFFLINE_COLOR},
  { nodes: ["福井県",	"愛知県"], color: OFFLINE_COLOR},
    
  { nodes: ["山梨県",	"神奈川県"], color: OFFLINE_COLOR},
  { nodes: ["山梨県",	"新潟県"], color: OFFLINE_COLOR},
  { nodes: ["山梨県",	"富山県"], color: OFFLINE_COLOR},
  { nodes: ["山梨県",	"石川県"], color: OFFLINE_COLOR},
  { nodes: ["山梨県",	"福井県"], color: OFFLINE_COLOR},
  { nodes: ["山梨県",	"長野県"], color: OFFLINE_COLOR},
  { nodes: ["山梨県",	"岐阜県"], color: OFFLINE_COLOR},
  { nodes: ["山梨県",	"静岡県"], color: OFFLINE_COLOR},
  { nodes: ["山梨県",	"愛知県"], color: OFFLINE_COLOR},
  { nodes: ["山梨県",	"三重県"], color: OFFLINE_COLOR},
    
  { nodes: ["長野県",	"新潟県"], color: OFFLINE_COLOR},
  { nodes: ["長野県",	"富山県"], color: OFFLINE_COLOR},
  { nodes: ["長野県",	"石川県"], color: OFFLINE_COLOR},
  { nodes: ["長野県",	"福井県"], color: OFFLINE_COLOR},
  { nodes: ["長野県",	"山梨県"], color: OFFLINE_COLOR},
  { nodes: ["長野県",	"岐阜県"], color: OFFLINE_COLOR},
  { nodes: ["長野県",	"静岡県"], color: OFFLINE_COLOR},
  { nodes: ["長野県",	"愛知県"], color: OFFLINE_COLOR},
  { nodes: ["長野県",	"三重県"], color: OFFLINE_COLOR},
  { nodes: ["長野県",	"滋賀県"], color: OFFLINE_COLOR},
    
  { nodes: ["岐阜県",	"富山県"], color: OFFLINE_COLOR},
  { nodes: ["岐阜県",	"石川県"], color: OFFLINE_COLOR},
  { nodes: ["岐阜県",	"福井県"], color: OFFLINE_COLOR},
  { nodes: ["岐阜県",	"山梨県"], color: OFFLINE_COLOR},
  { nodes: ["岐阜県",	"長野県"], color: OFFLINE_COLOR},
  { nodes: ["岐阜県",	"静岡県"], color: OFFLINE_COLOR},
  { nodes: ["岐阜県",	"愛知県"], color: OFFLINE_COLOR},
  { nodes: ["岐阜県",	"三重県"], color: OFFLINE_COLOR},
  { nodes: ["岐阜県",	"滋賀県"], color: OFFLINE_COLOR},
  { nodes: ["岐阜県",	"京都府"], color: OFFLINE_COLOR},
    
  { nodes: ["静岡県",	"石川県"], color: OFFLINE_COLOR},
  { nodes: ["静岡県",	"福井県"], color: OFFLINE_COLOR},
  { nodes: ["静岡県",	"山梨県"], color: OFFLINE_COLOR},
  { nodes: ["静岡県",	"長野県"], color: OFFLINE_COLOR},
  { nodes: ["静岡県",	"岐阜県"], color: OFFLINE_COLOR},
  { nodes: ["静岡県",	"愛知県"], color: OFFLINE_COLOR},
  { nodes: ["静岡県",	"三重県"], color: OFFLINE_COLOR},
  { nodes: ["静岡県",	"滋賀県"], color: OFFLINE_COLOR},
  { nodes: ["静岡県",	"京都府"], color: OFFLINE_COLOR},
  { nodes: ["静岡県",	"大阪府"], color: OFFLINE_COLOR},
    
  { nodes: ["愛知県",	"福井県"], color: OFFLINE_COLOR},
  { nodes: ["愛知県",	"山梨県"], color: OFFLINE_COLOR},
  { nodes: ["愛知県",	"長野県"], color: OFFLINE_COLOR},
  { nodes: ["愛知県",	"岐阜県"], color: OFFLINE_COLOR},
  { nodes: ["愛知県",	"静岡県"], color: OFFLINE_COLOR},
  { nodes: ["愛知県",	"三重県"], color: OFFLINE_COLOR},
  { nodes: ["愛知県",	"滋賀県"], color: OFFLINE_COLOR},
  { nodes: ["愛知県",	"京都府"], color: OFFLINE_COLOR},
  { nodes: ["愛知県",	"大阪府"], color: OFFLINE_COLOR},
  { nodes: ["愛知県",	"兵庫県"], color: OFFLINE_COLOR},
    
  { nodes: ["三重県",	"山梨県"], color: OFFLINE_COLOR},
  { nodes: ["三重県",	"長野県"], color: OFFLINE_COLOR},
  { nodes: ["三重県",	"岐阜県"], color: OFFLINE_COLOR},
  { nodes: ["三重県",	"静岡県"], color: OFFLINE_COLOR},
  { nodes: ["三重県",	"愛知県"], color: OFFLINE_COLOR},
  { nodes: ["三重県",	"滋賀県"], color: OFFLINE_COLOR},
  { nodes: ["三重県",	"京都府"], color: OFFLINE_COLOR},
  { nodes: ["三重県",	"大阪府"], color: OFFLINE_COLOR},
  { nodes: ["三重県",	"兵庫県"], color: OFFLINE_COLOR},
  { nodes: ["三重県",	"奈良県"], color: OFFLINE_COLOR},
    
  { nodes: ["滋賀県",	"長野県"], color: OFFLINE_COLOR},
  { nodes: ["滋賀県",	"岐阜県"], color: OFFLINE_COLOR},
  { nodes: ["滋賀県",	"静岡県"], color: OFFLINE_COLOR},
  { nodes: ["滋賀県",	"愛知県"], color: OFFLINE_COLOR},
  { nodes: ["滋賀県",	"三重県"], color: OFFLINE_COLOR},
  { nodes: ["滋賀県",	"京都府"], color: OFFLINE_COLOR},
  { nodes: ["滋賀県",	"大阪府"], color: OFFLINE_COLOR},
  { nodes: ["滋賀県",	"兵庫県"], color: OFFLINE_COLOR},
  { nodes: ["滋賀県",	"奈良県"], color: OFFLINE_COLOR},
  { nodes: ["滋賀県",	"和歌山県"], color: OFFLINE_COLOR},
    
  { nodes: ["京都府",	"岐阜県"], color: OFFLINE_COLOR},
  { nodes: ["京都府",	"静岡県"], color: OFFLINE_COLOR},
  { nodes: ["京都府",	"愛知県"], color: OFFLINE_COLOR},
  { nodes: ["京都府",	"三重県"], color: OFFLINE_COLOR},
  { nodes: ["京都府",	"滋賀県"], color: OFFLINE_COLOR},
  { nodes: ["京都府",	"大阪府"], color: OFFLINE_COLOR},
  { nodes: ["京都府",	"兵庫県"], color: OFFLINE_COLOR},
  { nodes: ["京都府",	"奈良県"], color: OFFLINE_COLOR},
  { nodes: ["京都府",	"和歌山県"], color: OFFLINE_COLOR},
  { nodes: ["京都府",	"鳥取県"], color: OFFLINE_COLOR},
    
  { nodes: ["大阪府",	"静岡県"], color: OFFLINE_COLOR},
  { nodes: ["大阪府",	"愛知県"], color: OFFLINE_COLOR},
  { nodes: ["大阪府",	"三重県"], color: OFFLINE_COLOR},
  { nodes: ["大阪府",	"滋賀県"], color: OFFLINE_COLOR},
  { nodes: ["大阪府",	"京都府"], color: OFFLINE_COLOR},
  { nodes: ["大阪府",	"兵庫県"], color: OFFLINE_COLOR},
  { nodes: ["大阪府",	"奈良県"], color: OFFLINE_COLOR},
  { nodes: ["大阪府",	"和歌山県"], color: OFFLINE_COLOR},
  { nodes: ["大阪府",	"鳥取県"], color: OFFLINE_COLOR},
  { nodes: ["大阪府",	"島根県"], color: OFFLINE_COLOR},
    
  { nodes: ["兵庫県",	"愛知県"], color: OFFLINE_COLOR},
  { nodes: ["兵庫県",	"三重県"], color: OFFLINE_COLOR},
  { nodes: ["兵庫県",	"滋賀県"], color: OFFLINE_COLOR},
  { nodes: ["兵庫県",	"京都府"], color: OFFLINE_COLOR},
  { nodes: ["兵庫県",	"大阪府"], color: OFFLINE_COLOR},
  { nodes: ["兵庫県",	"奈良県"], color: OFFLINE_COLOR},
  { nodes: ["兵庫県",	"和歌山県"], color: OFFLINE_COLOR},
  { nodes: ["兵庫県",	"鳥取県"], color: OFFLINE_COLOR},
  { nodes: ["兵庫県",	"島根県"], color: OFFLINE_COLOR},
  { nodes: ["兵庫県",	"岡山県"], color: OFFLINE_COLOR},
    
  { nodes: ["奈良県",	"三重県"], color: OFFLINE_COLOR},
  { nodes: ["奈良県",	"滋賀県"], color: OFFLINE_COLOR},
  { nodes: ["奈良県",	"京都府"], color: OFFLINE_COLOR},
  { nodes: ["奈良県",	"大阪府"], color: OFFLINE_COLOR},
  { nodes: ["奈良県",	"兵庫県"], color: OFFLINE_COLOR},
  { nodes: ["奈良県",	"和歌山県"], color: OFFLINE_COLOR},
  { nodes: ["奈良県",	"鳥取県"], color: OFFLINE_COLOR},
  { nodes: ["奈良県",	"島根県"], color: OFFLINE_COLOR},
  { nodes: ["奈良県",	"岡山県"], color: OFFLINE_COLOR},
  { nodes: ["奈良県",	"広島県"], color: OFFLINE_COLOR},
    
  { nodes: ["和歌山県",	"滋賀県"], color: OFFLINE_COLOR},
  { nodes: ["和歌山県",	"京都府"], color: OFFLINE_COLOR},
  { nodes: ["和歌山県",	"大阪府"], color: OFFLINE_COLOR},
  { nodes: ["和歌山県",	"兵庫県"], color: OFFLINE_COLOR},
  { nodes: ["和歌山県",	"奈良県"], color: OFFLINE_COLOR},
  { nodes: ["和歌山県",	"鳥取県"], color: OFFLINE_COLOR},
  { nodes: ["和歌山県",	"島根県"], color: OFFLINE_COLOR},
  { nodes: ["和歌山県",	"岡山県"], color: OFFLINE_COLOR},
  { nodes: ["和歌山県",	"広島県"], color: OFFLINE_COLOR},
  { nodes: ["和歌山県",	"山口県"], color: OFFLINE_COLOR},
    
  { nodes: ["鳥取県",	"京都府"], color: OFFLINE_COLOR},
  { nodes: ["鳥取県",	"大阪府"], color: OFFLINE_COLOR},
  { nodes: ["鳥取県",	"兵庫県"], color: OFFLINE_COLOR},
  { nodes: ["鳥取県",	"奈良県"], color: OFFLINE_COLOR},
  { nodes: ["鳥取県",	"和歌山県"], color: OFFLINE_COLOR},
  { nodes: ["鳥取県",	"島根県"], color: OFFLINE_COLOR},
  { nodes: ["鳥取県",	"岡山県"], color: OFFLINE_COLOR},
  { nodes: ["鳥取県",	"広島県"], color: OFFLINE_COLOR},
  { nodes: ["鳥取県",	"山口県"], color: OFFLINE_COLOR},
  { nodes: ["鳥取県",	"徳島県"], color: OFFLINE_COLOR},
    
  { nodes: ["島根県",	"大阪府"], color: OFFLINE_COLOR},
  { nodes: ["島根県",	"兵庫県"], color: OFFLINE_COLOR},
  { nodes: ["島根県",	"奈良県"], color: OFFLINE_COLOR},
  { nodes: ["島根県",	"和歌山県"], color: OFFLINE_COLOR},
  { nodes: ["島根県",	"鳥取県"], color: OFFLINE_COLOR},
  { nodes: ["島根県",	"岡山県"], color: OFFLINE_COLOR},
  { nodes: ["島根県",	"広島県"], color: OFFLINE_COLOR},
  { nodes: ["島根県",	"山口県"], color: OFFLINE_COLOR},
  { nodes: ["島根県",	"徳島県"], color: OFFLINE_COLOR},
  { nodes: ["島根県",	"香川県"], color: OFFLINE_COLOR},

  { nodes: ["岡山県",	"兵庫県"], color: OFFLINE_COLOR},
  { nodes: ["岡山県",	"奈良県"], color: OFFLINE_COLOR},
  { nodes: ["岡山県",	"和歌山県"], color: OFFLINE_COLOR},
  { nodes: ["岡山県",	"鳥取県"], color: OFFLINE_COLOR},
  { nodes: ["岡山県",	"島根県"], color: OFFLINE_COLOR},
  { nodes: ["岡山県",	"広島県"], color: OFFLINE_COLOR},
  { nodes: ["岡山県",	"山口県"], color: OFFLINE_COLOR},
  { nodes: ["岡山県",	"徳島県"], color: OFFLINE_COLOR},
  { nodes: ["岡山県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["岡山県",	"愛媛県"], color: OFFLINE_COLOR},
    
  { nodes: ["広島県",	"奈良県"], color: OFFLINE_COLOR},
  { nodes: ["広島県",	"和歌山県"], color: OFFLINE_COLOR},
  { nodes: ["広島県",	"鳥取県"], color: OFFLINE_COLOR},
  { nodes: ["広島県",	"島根県"], color: OFFLINE_COLOR},
  { nodes: ["広島県",	"岡山県"], color: OFFLINE_COLOR},
  { nodes: ["広島県",	"山口県"], color: OFFLINE_COLOR},
  { nodes: ["広島県",	"徳島県"], color: OFFLINE_COLOR},
  { nodes: ["広島県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["広島県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["広島県",	"高知県"], color: OFFLINE_COLOR},
    
  { nodes: ["山口県",	"和歌山県"], color: OFFLINE_COLOR},
  { nodes: ["山口県",	"鳥取県"], color: OFFLINE_COLOR},
  { nodes: ["山口県",	"島根県"], color: OFFLINE_COLOR},
  { nodes: ["山口県",	"岡山県"], color: OFFLINE_COLOR},
  { nodes: ["山口県",	"広島県"], color: OFFLINE_COLOR},
  { nodes: ["山口県",	"徳島県"], color: OFFLINE_COLOR},
  { nodes: ["山口県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["山口県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["山口県",	"高知県"], color: OFFLINE_COLOR},
  { nodes: ["山口県",	"福岡県"], color: OFFLINE_COLOR},
    
  { nodes: ["徳島県",	"鳥取県"], color: OFFLINE_COLOR},
  { nodes: ["徳島県",	"島根県"], color: OFFLINE_COLOR},
  { nodes: ["徳島県",	"岡山県"], color: OFFLINE_COLOR},
  { nodes: ["徳島県",	"広島県"], color: OFFLINE_COLOR},
  { nodes: ["徳島県",	"山口県"], color: OFFLINE_COLOR},
  { nodes: ["徳島県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["徳島県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["徳島県",	"高知県"], color: OFFLINE_COLOR},
  { nodes: ["徳島県",	"福岡県"], color: OFFLINE_COLOR},
  { nodes: ["徳島県",	"佐賀県"], color: OFFLINE_COLOR},
    
  { nodes: ["香川県",	"島根県"], color: OFFLINE_COLOR},
  { nodes: ["香川県",	"岡山県"], color: OFFLINE_COLOR},
  { nodes: ["香川県",	"広島県"], color: OFFLINE_COLOR},
  { nodes: ["香川県",	"山口県"], color: OFFLINE_COLOR},
  { nodes: ["香川県",	"徳島県"], color: OFFLINE_COLOR},
  { nodes: ["香川県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["香川県",	"高知県"], color: OFFLINE_COLOR},
  { nodes: ["香川県",	"福岡県"], color: OFFLINE_COLOR},
  { nodes: ["香川県",	"佐賀県"], color: OFFLINE_COLOR},
  { nodes: ["香川県",	"長崎県"], color: OFFLINE_COLOR},
    
  { nodes: ["愛媛県",	"岡山県"], color: OFFLINE_COLOR},
  { nodes: ["愛媛県",	"広島県"], color: OFFLINE_COLOR},
  { nodes: ["愛媛県",	"山口県"], color: OFFLINE_COLOR},
  { nodes: ["愛媛県",	"徳島県"], color: OFFLINE_COLOR},
  { nodes: ["愛媛県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["愛媛県",	"高知県"], color: OFFLINE_COLOR},
  { nodes: ["愛媛県",	"福岡県"], color: OFFLINE_COLOR},
  { nodes: ["愛媛県",	"佐賀県"], color: OFFLINE_COLOR},
  { nodes: ["愛媛県",	"長崎県"], color: OFFLINE_COLOR},
  { nodes: ["愛媛県",	"熊本県"], color: OFFLINE_COLOR},
    
  { nodes: ["高知県",	"広島県"], color: OFFLINE_COLOR},
  { nodes: ["高知県",	"山口県"], color: OFFLINE_COLOR},
  { nodes: ["高知県",	"徳島県"], color: OFFLINE_COLOR},
  { nodes: ["高知県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["高知県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["高知県",	"福岡県"], color: OFFLINE_COLOR},
  { nodes: ["高知県",	"佐賀県"], color: OFFLINE_COLOR},
  { nodes: ["高知県",	"長崎県"], color: OFFLINE_COLOR},
  { nodes: ["高知県",	"熊本県"], color: OFFLINE_COLOR},
  { nodes: ["高知県",	"大分県"], color: OFFLINE_COLOR},
    
  { nodes: ["福岡県",	"山口県"], color: OFFLINE_COLOR},
  { nodes: ["福岡県",	"徳島県"], color: OFFLINE_COLOR},
  { nodes: ["福岡県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["福岡県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["福岡県",	"高知県"], color: OFFLINE_COLOR},
  { nodes: ["福岡県",	"佐賀県"], color: OFFLINE_COLOR},
  { nodes: ["福岡県",	"長崎県"], color: OFFLINE_COLOR},
  { nodes: ["福岡県",	"熊本県"], color: OFFLINE_COLOR},
  { nodes: ["福岡県",	"大分県"], color: OFFLINE_COLOR},
  { nodes: ["福岡県",	"宮崎県"], color: OFFLINE_COLOR},
    
  { nodes: ["佐賀県",	"徳島県"], color: OFFLINE_COLOR},
  { nodes: ["佐賀県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["佐賀県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["佐賀県",	"高知県"], color: OFFLINE_COLOR},
  { nodes: ["佐賀県",	"福岡県"], color: OFFLINE_COLOR},
  { nodes: ["佐賀県",	"長崎県"], color: OFFLINE_COLOR},
  { nodes: ["佐賀県",	"熊本県"], color: OFFLINE_COLOR},
  { nodes: ["佐賀県",	"大分県"], color: OFFLINE_COLOR},
  { nodes: ["佐賀県",	"宮崎県"], color: OFFLINE_COLOR},
  { nodes: ["佐賀県",	"鹿児島県"], color: OFFLINE_COLOR},
    
  { nodes: ["長崎県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["長崎県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["長崎県",	"高知県"], color: OFFLINE_COLOR},
  { nodes: ["長崎県",	"福岡県"], color: OFFLINE_COLOR},
  { nodes: ["長崎県",	"佐賀県"], color: OFFLINE_COLOR},
  { nodes: ["長崎県",	"熊本県"], color: OFFLINE_COLOR},
  { nodes: ["長崎県",	"大分県"], color: OFFLINE_COLOR},
  { nodes: ["長崎県",	"宮崎県"], color: OFFLINE_COLOR},
  { nodes: ["長崎県",	"鹿児島県"], color: OFFLINE_COLOR},
  { nodes: ["長崎県",	"沖縄県"], color: OFFLINE_COLOR},
    
  { nodes: ["熊本県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["熊本県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["熊本県",	"高知県"], color: OFFLINE_COLOR},
  { nodes: ["熊本県",	"福岡県"], color: OFFLINE_COLOR},
  { nodes: ["熊本県",	"佐賀県"], color: OFFLINE_COLOR},
  { nodes: ["熊本県",	"長崎県"], color: OFFLINE_COLOR},
  { nodes: ["熊本県",	"大分県"], color: OFFLINE_COLOR},
  { nodes: ["熊本県",	"宮崎県"], color: OFFLINE_COLOR},
  { nodes: ["熊本県",	"鹿児島県"], color: OFFLINE_COLOR},
  { nodes: ["熊本県",	"沖縄県"], color: OFFLINE_COLOR},
    
  { nodes: ["大分県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["大分県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["大分県",	"高知県"], color: OFFLINE_COLOR},
  { nodes: ["大分県",	"福岡県"], color: OFFLINE_COLOR},
  { nodes: ["大分県",	"佐賀県"], color: OFFLINE_COLOR},
  { nodes: ["大分県",	"長崎県"], color: OFFLINE_COLOR},
  { nodes: ["大分県",	"熊本県"], color: OFFLINE_COLOR},
  { nodes: ["大分県",	"宮崎県"], color: OFFLINE_COLOR},
  { nodes: ["大分県",	"鹿児島県"], color: OFFLINE_COLOR},
  { nodes: ["大分県",	"沖縄県"], color: OFFLINE_COLOR},
    
  { nodes: ["宮崎県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["宮崎県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["宮崎県",	"高知県"], color: OFFLINE_COLOR},
  { nodes: ["宮崎県",	"福岡県"], color: OFFLINE_COLOR},
  { nodes: ["宮崎県",	"佐賀県"], color: OFFLINE_COLOR},
  { nodes: ["宮崎県",	"長崎県"], color: OFFLINE_COLOR},
  { nodes: ["宮崎県",	"熊本県"], color: OFFLINE_COLOR},
  { nodes: ["宮崎県",	"大分県"], color: OFFLINE_COLOR},
  { nodes: ["宮崎県",	"鹿児島県"], color: OFFLINE_COLOR},
  { nodes: ["宮崎県",	"沖縄県"], color: OFFLINE_COLOR},
    
  { nodes: ["鹿児島県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["鹿児島県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["鹿児島県",	"高知県"], color: OFFLINE_COLOR},
  { nodes: ["鹿児島県",	"福岡県"], color: OFFLINE_COLOR},
  { nodes: ["鹿児島県",	"佐賀県"], color: OFFLINE_COLOR},
  { nodes: ["鹿児島県",	"長崎県"], color: OFFLINE_COLOR},
  { nodes: ["鹿児島県",	"熊本県"], color: OFFLINE_COLOR},
  { nodes: ["鹿児島県",	"大分県"], color: OFFLINE_COLOR},
  { nodes: ["鹿児島県",	"宮崎県"], color: OFFLINE_COLOR},
  { nodes: ["鹿児島県",	"沖縄県"], color: OFFLINE_COLOR},
    
  { nodes: ["沖縄県",	"香川県"], color: OFFLINE_COLOR},
  { nodes: ["沖縄県",	"愛媛県"], color: OFFLINE_COLOR},
  { nodes: ["沖縄県",	"高知県"], color: OFFLINE_COLOR},
  { nodes: ["沖縄県",	"福岡県"], color: OFFLINE_COLOR},
  { nodes: ["沖縄県",	"佐賀県"], color: OFFLINE_COLOR},
  { nodes: ["沖縄県",	"長崎県"], color: OFFLINE_COLOR},
  { nodes: ["沖縄県",	"熊本県"], color: OFFLINE_COLOR},
  { nodes: ["沖縄県",	"大分県"], color: OFFLINE_COLOR},
  { nodes: ["沖縄県",	"宮崎県"], color: OFFLINE_COLOR},
  { nodes: ["沖縄県",	"鹿児島県"], color: OFFLINE_COLOR},

  // ONLINE
  { nodes: ["北海道",	"鳥取県"], color: ONLINE_COLOR},
  { nodes: ["北海道",	"熊本県"], color: ONLINE_COLOR},
  { nodes: ["北海道",	"千葉県"], color: ONLINE_COLOR},
  { nodes: ["北海道",	"奈良県"], color: ONLINE_COLOR},
  { nodes: ["北海道",	"徳島県"], color: ONLINE_COLOR},
  { nodes: ["北海道",	"埼玉県"], color: ONLINE_COLOR},
  { nodes: ["北海道",	"和歌山県"], color: ONLINE_COLOR},
  { nodes: ["北海道",	"兵庫県"], color: ONLINE_COLOR},
  { nodes: ["北海道",	"佐賀県"], color: ONLINE_COLOR},
  { nodes: ["北海道",	"兵庫県"], color: ONLINE_COLOR},
  
  { nodes: ["青森県",	"鹿児島県"], color: ONLINE_COLOR},
  { nodes: ["青森県",	"香川県"], color: ONLINE_COLOR},
  { nodes: ["青森県",	"愛媛県"], color: ONLINE_COLOR},
  { nodes: ["青森県",	"青森県"], color: ONLINE_COLOR},
  { nodes: ["青森県",	"新潟県"], color: ONLINE_COLOR},
  { nodes: ["青森県",	"京都府"], color: ONLINE_COLOR},
  { nodes: ["青森県",	"京都府"], color: ONLINE_COLOR},
  { nodes: ["青森県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["青森県",	"香川県"], color: ONLINE_COLOR},
  { nodes: ["青森県",	"山梨県"], color: ONLINE_COLOR},

  { nodes: ["岩手県",	"群馬県"], color: ONLINE_COLOR},
  { nodes: ["岩手県",	"宮崎県"], color: ONLINE_COLOR},
  { nodes: ["岩手県",	"沖縄県"], color: ONLINE_COLOR},
  { nodes: ["岩手県",	"大分県"], color: ONLINE_COLOR},
  { nodes: ["岩手県",	"長崎県"], color: ONLINE_COLOR},
  { nodes: ["岩手県",	"福島県"], color: ONLINE_COLOR},
  { nodes: ["岩手県",	"広島県"], color: ONLINE_COLOR},
  { nodes: ["岩手県",	"佐賀県"], color: ONLINE_COLOR},
  { nodes: ["岩手県",	"愛知県"], color: ONLINE_COLOR},
  { nodes: ["岩手県",	"神奈川県"], color: ONLINE_COLOR},

  { nodes: ["宮城県",	"京都府"], color: ONLINE_COLOR},
  { nodes: ["宮城県",	"三重県"], color: ONLINE_COLOR},
  { nodes: ["宮城県",	"香川県"], color: ONLINE_COLOR},
  { nodes: ["宮城県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["宮城県",	"熊本県"], color: ONLINE_COLOR},
  { nodes: ["宮城県",	"香川県"], color: ONLINE_COLOR},
  { nodes: ["宮城県",	"三重県"], color: ONLINE_COLOR},
  { nodes: ["宮城県",	"福島県"], color: ONLINE_COLOR},
  { nodes: ["宮城県",	"福島県"], color: ONLINE_COLOR},
  { nodes: ["宮城県",	"宮崎県"], color: ONLINE_COLOR},
    
  { nodes: ["秋田県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["秋田県",	"福岡県"], color: ONLINE_COLOR},
  { nodes: ["秋田県",	"沖縄県"], color: ONLINE_COLOR},
  { nodes: ["秋田県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["秋田県",	"鳥取県"], color: ONLINE_COLOR},
  { nodes: ["秋田県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["秋田県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["秋田県",	"奈良県"], color: ONLINE_COLOR},
  { nodes: ["秋田県",	"千葉県"], color: ONLINE_COLOR},
  { nodes: ["秋田県",	"愛知県"], color: ONLINE_COLOR},
    
  { nodes: ["山形県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["山形県",	"愛媛県"], color: ONLINE_COLOR},
  { nodes: ["山形県",	"香川県"], color: ONLINE_COLOR},
  { nodes: ["山形県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["山形県",	"香川県"], color: ONLINE_COLOR},
  { nodes: ["山形県",	"宮崎県"], color: ONLINE_COLOR},
  { nodes: ["山形県",	"熊本県"], color: ONLINE_COLOR},
  { nodes: ["山形県",	"長野県"], color: ONLINE_COLOR},
  { nodes: ["山形県",	"高知県"], color: ONLINE_COLOR},
  { nodes: ["山形県",	"栃木県"], color: ONLINE_COLOR},
    
  { nodes: ["福島県",	"京都府"], color: ONLINE_COLOR},
  { nodes: ["福島県",	"富山県"], color: ONLINE_COLOR},
  { nodes: ["福島県",	"青森県"], color: ONLINE_COLOR},
  { nodes: ["福島県",	"静岡県"], color: ONLINE_COLOR},
  { nodes: ["福島県",	"京都府"], color: ONLINE_COLOR},
  { nodes: ["福島県",	"千葉県"], color: ONLINE_COLOR},
  { nodes: ["福島県",	"奈良県"], color: ONLINE_COLOR},
  { nodes: ["福島県",	"富山県"], color: ONLINE_COLOR},
  { nodes: ["福島県",	"福井県"], color: ONLINE_COLOR},
  { nodes: ["福島県",	"山口県"], color: ONLINE_COLOR},

  { nodes: ["茨城県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["茨城県",	"静岡県"], color: ONLINE_COLOR},
  { nodes: ["茨城県",	"島根県"], color: ONLINE_COLOR},
  { nodes: ["茨城県",	"鳥取県"], color: ONLINE_COLOR},
  { nodes: ["茨城県",	"島根県"], color: ONLINE_COLOR},
  { nodes: ["茨城県",	"広島県"], color: ONLINE_COLOR},
  { nodes: ["茨城県",	"島根県"], color: ONLINE_COLOR},
  { nodes: ["茨城県",	"静岡県"], color: ONLINE_COLOR},
  { nodes: ["茨城県",	"長崎県"], color: ONLINE_COLOR},
  { nodes: ["茨城県",	"大阪府"], color: ONLINE_COLOR},
    
  { nodes: ["栃木県",	"埼玉県"], color: ONLINE_COLOR},
  { nodes: ["栃木県",	"山口県"], color: ONLINE_COLOR},
  { nodes: ["栃木県",	"茨城県"], color: ONLINE_COLOR},
  { nodes: ["栃木県",	"滋賀県"], color: ONLINE_COLOR},
  { nodes: ["栃木県",	"兵庫県"], color: ONLINE_COLOR},
  { nodes: ["栃木県",	"長崎県"], color: ONLINE_COLOR},
  { nodes: ["栃木県",	"東京都"], color: ONLINE_COLOR},
  { nodes: ["栃木県",	"茨城県"], color: ONLINE_COLOR},
  { nodes: ["栃木県",	"山形県"], color: ONLINE_COLOR},
  { nodes: ["栃木県",	"宮城県"], color: ONLINE_COLOR},
    
  { nodes: ["群馬県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["群馬県",	"茨城県"], color: ONLINE_COLOR},
  { nodes: ["群馬県",	"石川県"], color: ONLINE_COLOR},
  { nodes: ["群馬県",	"茨城県"], color: ONLINE_COLOR},
  { nodes: ["群馬県",	"鹿児島県"], color: ONLINE_COLOR},
  { nodes: ["群馬県",	"千葉県"], color: ONLINE_COLOR},
  { nodes: ["群馬県",	"山口県"], color: ONLINE_COLOR},
  { nodes: ["群馬県",	"栃木県"], color: ONLINE_COLOR},
  { nodes: ["群馬県",	"宮崎県"], color: ONLINE_COLOR},
  { nodes: ["群馬県",	"鳥取県"], color: ONLINE_COLOR},
    
  { nodes: ["埼玉県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["埼玉県",	"広島県"], color: ONLINE_COLOR},
  { nodes: ["埼玉県",	"福井県"], color: ONLINE_COLOR},
  { nodes: ["埼玉県",	"福井県"], color: ONLINE_COLOR},
  { nodes: ["埼玉県",	"徳島県"], color: ONLINE_COLOR},
  { nodes: ["埼玉県",	"栃木県"], color: ONLINE_COLOR},
  { nodes: ["埼玉県",	"新潟県"], color: ONLINE_COLOR},
  { nodes: ["埼玉県",	"愛媛県"], color: ONLINE_COLOR},
  { nodes: ["埼玉県",	"大分県"], color: ONLINE_COLOR},
  { nodes: ["埼玉県",	"岐阜県"], color: ONLINE_COLOR},
    
  { nodes: ["千葉県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["千葉県",	"熊本県"], color: ONLINE_COLOR},
  { nodes: ["千葉県",	"愛媛県"], color: ONLINE_COLOR},
  { nodes: ["千葉県",	"長野県"], color: ONLINE_COLOR},
  { nodes: ["千葉県",	"沖縄県"], color: ONLINE_COLOR},
  { nodes: ["千葉県",	"和歌山県"], color: ONLINE_COLOR},
  { nodes: ["千葉県",	"佐賀県"], color: ONLINE_COLOR},
  { nodes: ["千葉県",	"広島県"], color: ONLINE_COLOR},
  { nodes: ["千葉県",	"群馬県"], color: ONLINE_COLOR},
  { nodes: ["千葉県",	"富山県"], color: ONLINE_COLOR},
    
  { nodes: ["東京都",	"香川県"], color: ONLINE_COLOR},
  { nodes: ["東京都",	"静岡県"], color: ONLINE_COLOR},
  { nodes: ["東京都",	"新潟県"], color: ONLINE_COLOR},
  { nodes: ["東京都",	"北海道"], color: ONLINE_COLOR},
  { nodes: ["東京都",	"福岡県"], color: ONLINE_COLOR},
  { nodes: ["東京都",	"高知県"], color: ONLINE_COLOR},
  { nodes: ["東京都",	"熊本県"], color: ONLINE_COLOR},
  { nodes: ["東京都",	"岐阜県"], color: ONLINE_COLOR},
  { nodes: ["東京都",	"京都府"], color: ONLINE_COLOR},
  { nodes: ["東京都",	"山口県"], color: ONLINE_COLOR},
    
  { nodes: ["神奈川県",	"岩手県"], color: ONLINE_COLOR},
  { nodes: ["神奈川県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["神奈川県",	"岡山県"], color: ONLINE_COLOR},
  { nodes: ["神奈川県",	"鳥取県"], color: ONLINE_COLOR},
  { nodes: ["神奈川県",	"福島県"], color: ONLINE_COLOR},
  { nodes: ["神奈川県",	"滋賀県"], color: ONLINE_COLOR},
  { nodes: ["神奈川県",	"京都府"], color: ONLINE_COLOR},
  { nodes: ["神奈川県",	"岩手県"], color: ONLINE_COLOR},
  { nodes: ["神奈川県",	"鹿児島県"], color: ONLINE_COLOR},
  { nodes: ["神奈川県",	"千葉県"], color: ONLINE_COLOR},
    
  { nodes: ["新潟県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["新潟県",	"栃木県"], color: ONLINE_COLOR},
  { nodes: ["新潟県",	"高知県"], color: ONLINE_COLOR},
  { nodes: ["新潟県",	"群馬県"], color: ONLINE_COLOR},
  { nodes: ["新潟県",	"大分県"], color: ONLINE_COLOR},
  { nodes: ["新潟県",	"石川県"], color: ONLINE_COLOR},
  { nodes: ["新潟県",	"福井県"], color: ONLINE_COLOR},
  { nodes: ["新潟県",	"大分県"], color: ONLINE_COLOR},
  { nodes: ["新潟県",	"鹿児島県"], color: ONLINE_COLOR},
  { nodes: ["新潟県",	"滋賀県"], color: ONLINE_COLOR},
    
  { nodes: ["富山県",	"福岡県"], color: ONLINE_COLOR},
  { nodes: ["富山県",	"佐賀県"], color: ONLINE_COLOR},
  { nodes: ["富山県",	"兵庫県"], color: ONLINE_COLOR},
  { nodes: ["富山県",	"京都府"], color: ONLINE_COLOR},
  { nodes: ["富山県",	"香川県"], color: ONLINE_COLOR},
  { nodes: ["富山県",	"福島県"], color: ONLINE_COLOR},
  { nodes: ["富山県",	"福井県"], color: ONLINE_COLOR},
  { nodes: ["富山県",	"千葉県"], color: ONLINE_COLOR},
  { nodes: ["富山県",	"山口県"], color: ONLINE_COLOR},
  { nodes: ["富山県",	"鳥取県"], color: ONLINE_COLOR},
    
  { nodes: ["石川県",	"岐阜県"], color: ONLINE_COLOR},
  { nodes: ["石川県",	"石川県"], color: ONLINE_COLOR},
  { nodes: ["石川県",	"山口県"], color: ONLINE_COLOR},
  { nodes: ["石川県",	"広島県"], color: ONLINE_COLOR},
  { nodes: ["石川県",	"長野県"], color: ONLINE_COLOR},
  { nodes: ["石川県",	"熊本県"], color: ONLINE_COLOR},
  { nodes: ["石川県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["石川県",	"栃木県"], color: ONLINE_COLOR},
  { nodes: ["石川県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["石川県",	"大阪府"], color: ONLINE_COLOR},
    
  { nodes: ["福井県",	"滋賀県"], color: ONLINE_COLOR},
  { nodes: ["福井県",	"広島県"], color: ONLINE_COLOR},
  { nodes: ["福井県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["福井県",	"広島県"], color: ONLINE_COLOR},
  { nodes: ["福井県",	"島根県"], color: ONLINE_COLOR},
  { nodes: ["福井県",	"新潟県"], color: ONLINE_COLOR},
  { nodes: ["福井県",	"香川県"], color: ONLINE_COLOR},
  { nodes: ["福井県",	"徳島県"], color: ONLINE_COLOR},
  { nodes: ["福井県",	"富山県"], color: ONLINE_COLOR},
  { nodes: ["福井県",	"島根県"], color: ONLINE_COLOR},
    
  { nodes: ["山梨県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["山梨県",	"神奈川県"], color: ONLINE_COLOR},
  { nodes: ["山梨県",	"熊本県"], color: ONLINE_COLOR},
  { nodes: ["山梨県",	"富山県"], color: ONLINE_COLOR},
  { nodes: ["山梨県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["山梨県",	"東京都"], color: ONLINE_COLOR},
  { nodes: ["山梨県",	"大分県"], color: ONLINE_COLOR},
  { nodes: ["山梨県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["山梨県",	"鹿児島県"], color: ONLINE_COLOR},
  { nodes: ["山梨県",	"茨城県"], color: ONLINE_COLOR},
    
  { nodes: ["長野県",	"徳島県"], color: ONLINE_COLOR},
  { nodes: ["長野県",	"兵庫県"], color: ONLINE_COLOR},
  { nodes: ["長野県",	"京都府"], color: ONLINE_COLOR},
  { nodes: ["長野県",	"大分県"], color: ONLINE_COLOR},
  { nodes: ["長野県",	"岡山県"], color: ONLINE_COLOR},
  { nodes: ["長野県",	"福井県"], color: ONLINE_COLOR},
  { nodes: ["長野県",	"岡山県"], color: ONLINE_COLOR},
  { nodes: ["長野県",	"千葉県"], color: ONLINE_COLOR},
  { nodes: ["長野県",	"神奈川県"], color: ONLINE_COLOR},
  { nodes: ["長野県",	"栃木県"], color: ONLINE_COLOR},
    
  { nodes: ["岐阜県",	"徳島県"], color: ONLINE_COLOR},
  { nodes: ["岐阜県",	"鹿児島県"], color: ONLINE_COLOR},
  { nodes: ["岐阜県",	"山口県"], color: ONLINE_COLOR},
  { nodes: ["岐阜県",	"兵庫県"], color: ONLINE_COLOR},
  { nodes: ["岐阜県",	"石川県"], color: ONLINE_COLOR},
  { nodes: ["岐阜県",	"長崎県"], color: ONLINE_COLOR},
  { nodes: ["岐阜県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["岐阜県",	"大分県"], color: ONLINE_COLOR},
  { nodes: ["岐阜県",	"香川県"], color: ONLINE_COLOR},
  { nodes: ["岐阜県",	"静岡県"], color: ONLINE_COLOR},
    
  { nodes: ["静岡県",	"三重県"], color: ONLINE_COLOR},
  { nodes: ["静岡県",	"滋賀県"], color: ONLINE_COLOR},
  { nodes: ["静岡県",	"茨城県"], color: ONLINE_COLOR},
  { nodes: ["静岡県",	"三重県"], color: ONLINE_COLOR},
  { nodes: ["静岡県",	"岡山県"], color: ONLINE_COLOR},
  { nodes: ["静岡県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["静岡県",	"群馬県"], color: ONLINE_COLOR},
  { nodes: ["静岡県",	"埼玉県"], color: ONLINE_COLOR},
  { nodes: ["静岡県",	"熊本県"], color: ONLINE_COLOR},
  { nodes: ["静岡県",	"熊本県"], color: ONLINE_COLOR},
    
  { nodes: ["愛知県",	"群馬県"], color: ONLINE_COLOR},
  { nodes: ["愛知県",	"和歌山県"], color: ONLINE_COLOR},
  { nodes: ["愛知県",	"千葉県"], color: ONLINE_COLOR},
  { nodes: ["愛知県",	"福井県"], color: ONLINE_COLOR},
  { nodes: ["愛知県",	"静岡県"], color: ONLINE_COLOR},
  { nodes: ["愛知県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["愛知県",	"山形県"], color: ONLINE_COLOR},
  { nodes: ["愛知県",	"奈良県"], color: ONLINE_COLOR},
  { nodes: ["愛知県",	"岩手県"], color: ONLINE_COLOR},
  { nodes: ["愛知県",	"三重県"], color: ONLINE_COLOR},
    
  { nodes: ["三重県",	"三重県"], color: ONLINE_COLOR},
  { nodes: ["三重県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["三重県",	"高知県"], color: ONLINE_COLOR},
  { nodes: ["三重県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["三重県",	"鳥取県"], color: ONLINE_COLOR},
  { nodes: ["三重県",	"山口県"], color: ONLINE_COLOR},
  { nodes: ["三重県",	"富山県"], color: ONLINE_COLOR},
  { nodes: ["三重県",	"兵庫県"], color: ONLINE_COLOR},
  { nodes: ["三重県",	"熊本県"], color: ONLINE_COLOR},
  { nodes: ["三重県",	"広島県"], color: ONLINE_COLOR},
    
  { nodes: ["滋賀県",	"茨城県"], color: ONLINE_COLOR},
  { nodes: ["滋賀県",	"鹿児島県"], color: ONLINE_COLOR},
  { nodes: ["滋賀県",	"香川県"], color: ONLINE_COLOR},
  { nodes: ["滋賀県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["滋賀県",	"岡山県"], color: ONLINE_COLOR},
  { nodes: ["滋賀県",	"群馬県"], color: ONLINE_COLOR},
  { nodes: ["滋賀県",	"福島県"], color: ONLINE_COLOR},
  { nodes: ["滋賀県",	"長崎県"], color: ONLINE_COLOR},
  { nodes: ["滋賀県",	"大分県"], color: ONLINE_COLOR},
  { nodes: ["滋賀県",	"福井県"], color: ONLINE_COLOR},
    
  { nodes: ["京都府",	"山形県"], color: ONLINE_COLOR},
  { nodes: ["京都府",	"大阪府"], color: ONLINE_COLOR},
  { nodes: ["京都府",	"奈良県"], color: ONLINE_COLOR},
  { nodes: ["京都府",	"福井県"], color: ONLINE_COLOR},
  { nodes: ["京都府",	"奈良県"], color: ONLINE_COLOR},
  { nodes: ["京都府",	"北海道"], color: ONLINE_COLOR},
  { nodes: ["京都府",	"石川県"], color: ONLINE_COLOR},
  { nodes: ["京都府",	"新潟県"], color: ONLINE_COLOR},
  { nodes: ["京都府",	"和歌山県"], color: ONLINE_COLOR},
  { nodes: ["京都府",	"熊本県"], color: ONLINE_COLOR},
    
  { nodes: ["大阪府",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["大阪府",	"群馬県"], color: ONLINE_COLOR},
  { nodes: ["大阪府",	"大阪府"], color: ONLINE_COLOR},
  { nodes: ["大阪府",	"福井県"], color: ONLINE_COLOR},
  { nodes: ["大阪府",	"東京都"], color: ONLINE_COLOR},
  { nodes: ["大阪府",	"岐阜県"], color: ONLINE_COLOR},
  { nodes: ["大阪府",	"長崎県"], color: ONLINE_COLOR},
  { nodes: ["大阪府",	"福岡県"], color: ONLINE_COLOR},
  { nodes: ["大阪府",	"福井県"], color: ONLINE_COLOR},
  { nodes: ["大阪府",	"宮城県"], color: ONLINE_COLOR},
    
  { nodes: ["兵庫県",	"滋賀県"], color: ONLINE_COLOR},
  { nodes: ["兵庫県",	"岡山県"], color: ONLINE_COLOR},
  { nodes: ["兵庫県",	"広島県"], color: ONLINE_COLOR},
  { nodes: ["兵庫県",	"青森県"], color: ONLINE_COLOR},
  { nodes: ["兵庫県",	"広島県"], color: ONLINE_COLOR},
  { nodes: ["兵庫県",	"滋賀県"], color: ONLINE_COLOR},
  { nodes: ["兵庫県",	"岡山県"], color: ONLINE_COLOR},
  { nodes: ["兵庫県",	"山形県"], color: ONLINE_COLOR},
  { nodes: ["兵庫県",	"静岡県"], color: ONLINE_COLOR},
  { nodes: ["兵庫県",	"石川県"], color: ONLINE_COLOR},
    
  { nodes: ["奈良県",	"福井県"], color: ONLINE_COLOR},
  { nodes: ["奈良県",	"山形県"], color: ONLINE_COLOR},
  { nodes: ["奈良県",	"福岡県"], color: ONLINE_COLOR},
  { nodes: ["奈良県",	"神奈川県"], color: ONLINE_COLOR},
  { nodes: ["奈良県",	"鹿児島県"], color: ONLINE_COLOR},
  { nodes: ["奈良県",	"京都府"], color: ONLINE_COLOR},
  { nodes: ["奈良県",	"熊本県"], color: ONLINE_COLOR},
  { nodes: ["奈良県",	"大阪府"], color: ONLINE_COLOR},
  { nodes: ["奈良県",	"奈良県"], color: ONLINE_COLOR},
  { nodes: ["奈良県",	"三重県"], color: ONLINE_COLOR},
    
  { nodes: ["和歌山県",	"滋賀県"], color: ONLINE_COLOR},
  { nodes: ["和歌山県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["和歌山県",	"大阪府"], color: ONLINE_COLOR},
  { nodes: ["和歌山県",	"鳥取県"], color: ONLINE_COLOR},
  { nodes: ["和歌山県",	"愛媛県"], color: ONLINE_COLOR},
  { nodes: ["和歌山県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["和歌山県",	"佐賀県"], color: ONLINE_COLOR},
  { nodes: ["和歌山県",	"山形県"], color: ONLINE_COLOR},
  { nodes: ["和歌山県",	"富山県"], color: ONLINE_COLOR},
  { nodes: ["和歌山県",	"山口県"], color: ONLINE_COLOR},
    
  { nodes: ["鳥取県",	"新潟県"], color: ONLINE_COLOR},
  { nodes: ["鳥取県",	"愛媛県"], color: ONLINE_COLOR},
  { nodes: ["鳥取県",	"熊本県"], color: ONLINE_COLOR},
  { nodes: ["鳥取県",	"島根県"], color: ONLINE_COLOR},
  { nodes: ["鳥取県",	"茨城県"], color: ONLINE_COLOR},
  { nodes: ["鳥取県",	"大阪府"], color: ONLINE_COLOR},
  { nodes: ["鳥取県",	"佐賀県"], color: ONLINE_COLOR},
  { nodes: ["鳥取県",	"青森県"], color: ONLINE_COLOR},
  { nodes: ["鳥取県",	"奈良県"], color: ONLINE_COLOR},
  { nodes: ["鳥取県",	"愛知県"], color: ONLINE_COLOR},
    
  { nodes: ["島根県",	"長野県"], color: ONLINE_COLOR},
  { nodes: ["島根県",	"富山県"], color: ONLINE_COLOR},
  { nodes: ["島根県",	"埼玉県"], color: ONLINE_COLOR},
  { nodes: ["島根県",	"高知県"], color: ONLINE_COLOR},
  { nodes: ["島根県",	"高知県"], color: ONLINE_COLOR},
  { nodes: ["島根県",	"岡山県"], color: ONLINE_COLOR},
  { nodes: ["島根県",	"鳥取県"], color: ONLINE_COLOR},
  { nodes: ["島根県",	"福井県"], color: ONLINE_COLOR},
  { nodes: ["島根県",	"神奈川県"], color: ONLINE_COLOR},
  { nodes: ["島根県",	"熊本県"], color: ONLINE_COLOR},

  { nodes: ["岡山県",	"宮崎県"], color: ONLINE_COLOR},
  { nodes: ["岡山県",	"徳島県"], color: ONLINE_COLOR},
  { nodes: ["岡山県",	"茨城県"], color: ONLINE_COLOR},
  { nodes: ["岡山県",	"石川県"], color: ONLINE_COLOR},
  { nodes: ["岡山県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["岡山県",	"京都府"], color: ONLINE_COLOR},
  { nodes: ["岡山県",	"愛知県"], color: ONLINE_COLOR},
  { nodes: ["岡山県",	"京都府"], color: ONLINE_COLOR},
  { nodes: ["岡山県",	"岐阜県"], color: ONLINE_COLOR},
  { nodes: ["岡山県",	"山梨県"], color: ONLINE_COLOR},
    
  { nodes: ["広島県",	"富山県"], color: ONLINE_COLOR},
  { nodes: ["広島県",	"山形県"], color: ONLINE_COLOR},
  { nodes: ["広島県",	"群馬県"], color: ONLINE_COLOR},
  { nodes: ["広島県",	"広島県"], color: ONLINE_COLOR},
  { nodes: ["広島県",	"佐賀県"], color: ONLINE_COLOR},
  { nodes: ["広島県",	"石川県"], color: ONLINE_COLOR},
  { nodes: ["広島県",	"愛媛県"], color: ONLINE_COLOR},
  { nodes: ["広島県",	"宮崎県"], color: ONLINE_COLOR},
  { nodes: ["広島県",	"山形県"], color: ONLINE_COLOR},
  { nodes: ["広島県",	"長崎県"], color: ONLINE_COLOR},
    
  { nodes: ["山口県",	"茨城県"], color: ONLINE_COLOR},
  { nodes: ["山口県",	"静岡県"], color: ONLINE_COLOR},
  { nodes: ["山口県",	"佐賀県"], color: ONLINE_COLOR},
  { nodes: ["山口県",	"茨城県"], color: ONLINE_COLOR},
  { nodes: ["山口県",	"岐阜県"], color: ONLINE_COLOR},
  { nodes: ["山口県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["山口県",	"石川県"], color: ONLINE_COLOR},
  { nodes: ["山口県",	"高知県"], color: ONLINE_COLOR},
  { nodes: ["山口県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["山口県",	"北海道"], color: ONLINE_COLOR},
    
  { nodes: ["徳島県",	"徳島県"], color: ONLINE_COLOR},
  { nodes: ["徳島県",	"宮崎県"], color: ONLINE_COLOR},
  { nodes: ["徳島県",	"兵庫県"], color: ONLINE_COLOR},
  { nodes: ["徳島県",	"香川県"], color: ONLINE_COLOR},
  { nodes: ["徳島県",	"三重県"], color: ONLINE_COLOR},
  { nodes: ["徳島県",	"和歌山県"], color: ONLINE_COLOR},
  { nodes: ["徳島県",	"静岡県"], color: ONLINE_COLOR},
  { nodes: ["徳島県",	"神奈川県"], color: ONLINE_COLOR},
  { nodes: ["徳島県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["徳島県",	"高知県"], color: ONLINE_COLOR},
    
  { nodes: ["香川県",	"東京都"], color: ONLINE_COLOR},
  { nodes: ["香川県",	"愛知県"], color: ONLINE_COLOR},
  { nodes: ["香川県",	"熊本県"], color: ONLINE_COLOR},
  { nodes: ["香川県",	"宮崎県"], color: ONLINE_COLOR},
  { nodes: ["香川県",	"宮崎県"], color: ONLINE_COLOR},
  { nodes: ["香川県",	"埼玉県"], color: ONLINE_COLOR},
  { nodes: ["香川県",	"埼玉県"], color: ONLINE_COLOR},
  { nodes: ["香川県",	"埼玉県"], color: ONLINE_COLOR},
  { nodes: ["香川県",	"埼玉県"], color: ONLINE_COLOR},
  { nodes: ["香川県",	"大阪府"], color: ONLINE_COLOR},
    
  { nodes: ["愛媛県",	"岐阜県"], color: ONLINE_COLOR},
  { nodes: ["愛媛県",	"佐賀県"], color: ONLINE_COLOR},
  { nodes: ["愛媛県",	"栃木県"], color: ONLINE_COLOR},
  { nodes: ["愛媛県",	"鹿児島県"], color: ONLINE_COLOR},
  { nodes: ["愛媛県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["愛媛県",	"大阪府"], color: ONLINE_COLOR},
  { nodes: ["愛媛県",	"兵庫県"], color: ONLINE_COLOR},
  { nodes: ["愛媛県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["愛媛県",	"徳島県"], color: ONLINE_COLOR},
  { nodes: ["愛媛県",	"茨城県"], color: ONLINE_COLOR},
    
  { nodes: ["高知県",	"島根県"], color: ONLINE_COLOR},
  { nodes: ["高知県",	"石川県"], color: ONLINE_COLOR},
  { nodes: ["高知県",	"島根県"], color: ONLINE_COLOR},
  { nodes: ["高知県",	"和歌山県"], color: ONLINE_COLOR},
  { nodes: ["高知県",	"岩手県"], color: ONLINE_COLOR},
  { nodes: ["高知県",	"鳥取県"], color: ONLINE_COLOR},
  { nodes: ["高知県",	"島根県"], color: ONLINE_COLOR},
  { nodes: ["高知県",	"沖縄県"], color: ONLINE_COLOR},
  { nodes: ["高知県",	"福島県"], color: ONLINE_COLOR},
  { nodes: ["高知県",	"愛媛県"], color: ONLINE_COLOR},
    
  { nodes: ["福岡県",	"大分県"], color: ONLINE_COLOR},
  { nodes: ["福岡県",	"東京都"], color: ONLINE_COLOR},
  { nodes: ["福岡県",	"宮崎県"], color: ONLINE_COLOR},
  { nodes: ["福岡県",	"埼玉県"], color: ONLINE_COLOR},
  { nodes: ["福岡県",	"岡山県"], color: ONLINE_COLOR},
  { nodes: ["福岡県",	"北海道"], color: ONLINE_COLOR},
  { nodes: ["福岡県",	"三重県"], color: ONLINE_COLOR},
  { nodes: ["福岡県",	"石川県"], color: ONLINE_COLOR},
  { nodes: ["福岡県",	"宮城県"], color: ONLINE_COLOR},
  { nodes: ["福岡県",	"香川県"], color: ONLINE_COLOR},
    
  { nodes: ["佐賀県",	"福岡県"], color: ONLINE_COLOR},
  { nodes: ["佐賀県",	"徳島県"], color: ONLINE_COLOR},
  { nodes: ["佐賀県",	"東京都"], color: ONLINE_COLOR},
  { nodes: ["佐賀県",	"群馬県"], color: ONLINE_COLOR},
  { nodes: ["佐賀県",	"高知県"], color: ONLINE_COLOR},
  { nodes: ["佐賀県",	"埼玉県"], color: ONLINE_COLOR},
  { nodes: ["佐賀県",	"福島県"], color: ONLINE_COLOR},
  { nodes: ["佐賀県",	"沖縄県"], color: ONLINE_COLOR},
  { nodes: ["佐賀県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["佐賀県",	"青森県"], color: ONLINE_COLOR},
    
  { nodes: ["長崎県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["長崎県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["長崎県",	"群馬県"], color: ONLINE_COLOR},
  { nodes: ["長崎県",	"愛知県"], color: ONLINE_COLOR},
  { nodes: ["長崎県",	"群馬県"], color: ONLINE_COLOR},
  { nodes: ["長崎県",	"愛媛県"], color: ONLINE_COLOR},
  { nodes: ["長崎県",	"山梨県"], color: ONLINE_COLOR},
  { nodes: ["長崎県",	"沖縄県"], color: ONLINE_COLOR},
  { nodes: ["長崎県",	"大阪府"], color: ONLINE_COLOR},
  { nodes: ["長崎県",	"愛媛県"], color: ONLINE_COLOR},
    
  { nodes: ["熊本県",	"栃木県"], color: ONLINE_COLOR},
  { nodes: ["熊本県",	"青森県"], color: ONLINE_COLOR},
  { nodes: ["熊本県",	"鹿児島県"], color: ONLINE_COLOR},
  { nodes: ["熊本県",	"鳥取県"], color: ONLINE_COLOR},
  { nodes: ["熊本県",	"長崎県"], color: ONLINE_COLOR},
  { nodes: ["熊本県",	"三重県"], color: ONLINE_COLOR},
  { nodes: ["熊本県",	"岡山県"], color: ONLINE_COLOR},
  { nodes: ["熊本県",	"滋賀県"], color: ONLINE_COLOR},
  { nodes: ["熊本県",	"石川県"], color: ONLINE_COLOR},
  { nodes: ["熊本県",	"福井県"], color: ONLINE_COLOR},
    
  { nodes: ["大分県",	"石川県"], color: ONLINE_COLOR},
  { nodes: ["大分県",	"和歌山県"], color: ONLINE_COLOR},
  { nodes: ["大分県",	"長野県"], color: ONLINE_COLOR},
  { nodes: ["大分県",	"静岡県"], color: ONLINE_COLOR},
  { nodes: ["大分県",	"長崎県"], color: ONLINE_COLOR},
  { nodes: ["大分県",	"三重県"], color: ONLINE_COLOR},
  { nodes: ["大分県",	"静岡県"], color: ONLINE_COLOR},
  { nodes: ["大分県",	"滋賀県"], color: ONLINE_COLOR},
  { nodes: ["大分県",	"栃木県"], color: ONLINE_COLOR},
  { nodes: ["大分県",	"山梨県"], color: ONLINE_COLOR},
    
  { nodes: ["宮崎県",	"東京都"], color: ONLINE_COLOR},
  { nodes: ["宮崎県",	"三重県"], color: ONLINE_COLOR},
  { nodes: ["宮崎県",	"兵庫県"], color: ONLINE_COLOR},
  { nodes: ["宮崎県",	"島根県"], color: ONLINE_COLOR},
  { nodes: ["宮崎県",	"秋田県"], color: ONLINE_COLOR},
  { nodes: ["宮崎県",	"埼玉県"], color: ONLINE_COLOR},
  { nodes: ["宮崎県",	"宮崎県"], color: ONLINE_COLOR},
  { nodes: ["宮崎県",	"大阪府"], color: ONLINE_COLOR},
  { nodes: ["宮崎県",	"長崎県"], color: ONLINE_COLOR},
  { nodes: ["宮崎県",	"山形県"], color: ONLINE_COLOR},
    
  { nodes: ["鹿児島県",	"宮崎県"], color: ONLINE_COLOR},
  { nodes: ["鹿児島県",	"広島県"], color: ONLINE_COLOR},
  { nodes: ["鹿児島県",	"岩手県"], color: ONLINE_COLOR},
  { nodes: ["鹿児島県",	"神奈川県"], color: ONLINE_COLOR},
  { nodes: ["鹿児島県",	"長崎県"], color: ONLINE_COLOR},
  { nodes: ["鹿児島県",	"愛媛県"], color: ONLINE_COLOR},
  { nodes: ["鹿児島県",	"兵庫県"], color: ONLINE_COLOR},
  { nodes: ["鹿児島県",	"宮崎県"], color: ONLINE_COLOR},
  { nodes: ["鹿児島県",	"長野県"], color: ONLINE_COLOR},
  { nodes: ["鹿児島県",	"島根県"], color: ONLINE_COLOR},
    
  { nodes: ["沖縄県",	"山口県"], color: ONLINE_COLOR},
  { nodes: ["沖縄県",	"三重県"], color: ONLINE_COLOR},
  { nodes: ["沖縄県",	"岩手県"], color: ONLINE_COLOR},
  { nodes: ["沖縄県",	"滋賀県"], color: ONLINE_COLOR},
  { nodes: ["沖縄県",	"広島県"], color: ONLINE_COLOR},
  { nodes: ["沖縄県",	"大分県"], color: ONLINE_COLOR},
  { nodes: ["沖縄県",	"高知県"], color: ONLINE_COLOR},
  { nodes: ["沖縄県",	"佐賀県"], color: ONLINE_COLOR},
  { nodes: ["沖縄県",	"新潟県"], color: ONLINE_COLOR},
  { nodes: ["沖縄県",	"長崎県"], color: ONLINE_COLOR},
]


export { dummyUsers, dummyEdge }
